package depcheck

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// dirtyTreeEvidence is git's refusal to touch a tree with local modifications —
// the condition the two known .beads files actually produce.
const dirtyTreeEvidence = "error: Your local changes to the following files would be overwritten by merge: .beads/config.yaml"

// TestBlockedMessageLeadsWithTheAnvilNotWithGit is the bead's headline: git's
// stderr used to BE the message, so a Needs Attention row opened with
// "fatal: ..." and said neither which anvil had stopped being scanned nor what
// to do about it. The evidence is still there — last, under its own label.
func TestBlockedMessageLeadsWithTheAnvilNotWithGit(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, "fatal: You are not currently on a branch.")

	assert.True(t, strings.HasPrefix(msg, "Anvil heimdall"), "the message opens with the anvil, got: %s", msg)
	assert.Contains(t, msg, "/srv/anvils/heimdall")
	assert.Contains(t, msg, "git output: fatal: You are not currently on a branch.")
	assert.Less(t, strings.Index(msg, "To resolve:"), strings.Index(msg, "git output:"),
		"git's own words are secondary — they come after the remediation")
}

// TestBlockedMessageOmitsAnEmptyGitOutput: the label is a promise that evidence
// follows it, so a failure that produced no text must not render an empty one.
func TestBlockedMessageOmitsAnEmptyGitOutput(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, "")

	assert.NotContains(t, msg, "git output:")
	assert.Contains(t, msg, "To resolve:")
}

// TestBlockedMessageAnnotatesTheKnownPaths is why the enumeration is worth
// anything: on a Forge-managed anvil the two paths an operator will most often
// see modified are ones they must NOT clean up, and a bare list of filenames
// says nothing about which is which.
func TestBlockedMessageAnnotatesTheKnownPaths(t *testing.T) {
	paths := []string{".beads/.gitignore", ".beads/config.yaml", "internal/foo.go"}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, "Blocking paths (3 paths)")
	assert.Contains(t, msg, ".beads/config.yaml (pod-local sync.remote override")
	assert.Contains(t, msg, ".beads/.gitignore (regenerated by bd")
	// The unexpected path is the one the remediation acts on; the two expected
	// ones are named in the list and left out of the command.
	assert.Contains(t, msg, "stash push -u -- internal/foo.go`, leaving the paths annotated as expected in place")
	assert.NotContains(t, msg, "stash push -u -- .beads")
}

// TestBlockedMessageWithOnlyExpectedPathsProposesNoCleanup: telling an operator
// to stash the pod-local .beads/config.yaml is telling them to break the
// anvil's beads connection. With nothing else modified there is no cleanup to
// propose and the message must say so instead of inventing one.
func TestBlockedMessageWithOnlyExpectedPathsProposesNoCleanup(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", []string{".beads/config.yaml", ".beads/.gitignore"}, dirtyTreeEvidence)

	assert.Contains(t, msg, "nothing unexpected is modified")
	assert.NotContains(t, msg, "stash push")
}

// TestBlockedMessageCapsThePathList: a checkout with a few hundred modified
// files would otherwise put the whole wall into a persisted row and push the
// remediation off the end of it. The count beside the list stays the full one.
func TestBlockedMessageCapsThePathList(t *testing.T) {
	var paths []string
	for i := 0; i < maxBlockingPathsListed+7; i++ {
		paths = append(paths, fmt.Sprintf("pkg/file%02d.go", i))
	}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, fmt.Sprintf("Blocking paths (%d paths)", len(paths)))
	assert.Contains(t, msg, "and 7 more")
	assert.NotContains(t, msg, "pkg/file20.go", "the 21st path is past the cap")
	// The command is capped harder than the list: a pasted line that wraps four
	// times is not a command an operator runs. What it must NOT do is describe
	// that partial command as dealing with "the unexpected changes" — pasted,
	// it clears five of twenty-seven paths and leaves the scan blocked while
	// reading like the fix.
	assert.Contains(t, msg, "stash push -u -- pkg/file00.go pkg/file01.go pkg/file02.go pkg/file03.go pkg/file04.go`")
	assert.Contains(t, msg, fmt.Sprintf("%d paths are unexpectedly modified, more than fit one command", len(paths)))
	assert.Contains(t, msg, "sets the first 5 aside")
	assert.Contains(t, msg, "repeat it for the rest")
	assert.NotContains(t, msg, "set the unexpected changes aside (recoverable) with `git -C /srv/anvils/heimdall stash push -u -- pkg/file00.go",
		"a command covering 5 of the paths must not be reported as covering the set")
	assert.NotContains(t, msg, "annotated as expected",
		"no path here is annotated as expected, so the message must not name a set the list above does not contain")
}

// TestBlockedMessageCommandCoversTheWholeSetAtTheCap: the boundary between the
// two remediation wordings. At exactly maxCommandPathsListed the pasted command
// IS the whole fix, so it must be reported as one rather than hedged.
func TestBlockedMessageCommandCoversTheWholeSetAtTheCap(t *testing.T) {
	var paths []string
	for i := 0; i < maxCommandPathsListed; i++ {
		paths = append(paths, fmt.Sprintf("pkg/file%02d.go", i))
	}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, "To resolve: set the unexpected changes aside (recoverable) with "+
		"`git -C /srv/anvils/heimdall stash push -u -- pkg/file00.go pkg/file01.go pkg/file02.go pkg/file03.go pkg/file04.go`.")
	assert.NotContains(t, msg, "more than fit one command")
}

// TestBlockedMessageKeepClauseFollowsTheRenderedList: the "leaving the paths
// annotated as expected in place" clause rests on an annotation the operator can
// SEE. An expected path past the list cap is not rendered, so a clause resting on
// it names a set the message does not contain — which reads as a path the render
// dropped.
func TestBlockedMessageKeepClauseFollowsTheRenderedList(t *testing.T) {
	var paths []string
	for i := 0; i < maxBlockingPathsListed; i++ {
		paths = append(paths, fmt.Sprintf("pkg/file%02d.go", i))
	}
	// Sorts last, so it lands past the cap and is never rendered.
	paths = append(paths, "zz/.beads/config.yaml")

	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.NotContains(t, msg, "zz/.beads/config.yaml", "the annotated path is past the list cap")
	assert.NotContains(t, msg, "annotated as expected",
		"the clause must not name an annotation the reader cannot check")
}

// TestBlockedMessageSanitisesPaths: a path comes out of a checkout Forge did not
// author and lands in daemon.log and an activity-feed row Hearth wraps without
// stripping — the same surfaces, and so the same treatment, as git's own words.
func TestBlockedMessageSanitisesPaths(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall",
		[]string{"pkg/\x1b[31mred\x1b[0m.go\nfatal: forged line"}, dirtyTreeEvidence)

	assert.NotContains(t, msg, "\x1b")
	assert.NotContains(t, msg, "\n")
	assert.Contains(t, msg, "pkg/red.go")
	// A path that did not survive sanitization intact is never written into a
	// command: pasted, it would name a different file.
	assert.Contains(t, msg, "stash push -u -- <path>")
}

// TestBlockedMessageOnlyEnumeratesWhenTheTreeIsTheBlocker: a detached HEAD is
// unaffected by what the tree holds, so listing a pod-local .beads/config.yaml
// as a "blocking path" would send the operator after a file that is fine.
func TestBlockedMessageOnlyEnumeratesWhenTheTreeIsTheBlocker(t *testing.T) {
	paths := []string{".beads/config.yaml"}

	detached := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, "fatal: You are not currently on a branch.")
	assert.NotContains(t, detached, "Blocking paths")
	assert.NotContains(t, detached, ".beads/config.yaml")
	assert.Contains(t, detached, "--set-upstream-to=origin/<branch>")

	dirty := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)
	assert.Contains(t, dirty, "Blocking paths")
}

// TestBlockedMessageRemediationPerCause: the command is the operator's whole
// next action, so each modelled condition gets its own — and an unmodelled one
// gets a diagnostic rather than a guess.
func TestBlockedMessageRemediationPerCause(t *testing.T) {
	cases := []struct {
		name     string
		evidence string
		wants    []string
	}{
		{"unmerged", "error: you have unmerged paths.", []string{"merge --abort"}},
		{"detached", "fatal: You are not currently on a branch.", []string{"checkout <branch>", "--set-upstream-to"}},
		{"no upstream", "resolving upstream for /srv/x: no upstream tracking ref", []string{"checkout <branch>"}},
		{"ref lock", "error: cannot lock ref 'refs/remotes/origin/main'", []string{"stale lock file", "/srv/anvils/heimdall/.git"}},
		{"not a repo", "fatal: not a git repository", []string{"forge anvil add heimdall"}},
		{"unmodelled", "fatal: refusing to merge unrelated histories", []string{"no specific", "git -C /srv/anvils/heimdall status"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, tc.evidence)
			for _, want := range tc.wants {
				assert.Contains(t, msg, want)
			}
		})
	}
}

// TestBlockedMessageWithoutACheckout: the path is optional at the call site, so
// the command must degrade to a template rather than render `git -C  status`.
func TestBlockedMessageWithoutACheckout(t *testing.T) {
	msg := blockedMessage("heimdall", "", nil, "fatal: You are not currently on a branch.")

	assert.NotContains(t, msg, "Checkout:")
	assert.Contains(t, msg, "git -C <checkout> checkout <branch>")
}

// TestParsePorcelain covers the entry shapes `git status --porcelain` produces:
// staged, unstaged, untracked, unmerged, and a rename — whose NEW path is the
// one present in the tree and the one a pathspec has to name.
func TestParsePorcelain(t *testing.T) {
	out := strings.Join([]string{
		" M .beads/config.yaml",
		"M  internal/foo.go",
		"?? scratch/notes.txt",
		"UU internal/conflict.go",
		"A  internal/foo.go", // a second entry for one path
		"R  old/name.go -> new/name.go",
		"",
	}, "\n")

	assert.Equal(t, []string{
		".beads/config.yaml",
		"internal/conflict.go",
		"internal/foo.go",
		"new/name.go",
		"scratch/notes.txt",
	}, parsePorcelain(out))
}

// TestParsePorcelainUnquotes: git C-quotes a path with anything special in it,
// and the quotes are git's syntax rather than part of the name.
func TestParsePorcelainUnquotes(t *testing.T) {
	assert.Equal(t, []string{"dir/a b.go"}, parsePorcelain(` M "dir/a b.go"`))
	assert.Equal(t, []string{"dir/é.go"}, parsePorcelain(` M "dir/\303\251.go"`))
	// A quoted value git wrote but Go refuses to decode keeps its content rather
	// than being dropped: an undecodable path is still one an operator knows.
	assert.Equal(t, []string{`dir/\q.go`}, parsePorcelain(` M "dir/\q.go"`))
}

// TestDirtyPathsAgainstARealCheckout drives the enumeration through git itself,
// since the parse is only as good as the format it was written against.
func TestDirtyPathsAgainstARealCheckout(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{
		".beads/config.yaml": "sync:\n  remote: upstream\n",
		"internal/foo.go":    "package internal\n",
	})
	writeFiles(t, clone, map[string]string{
		".beads/config.yaml": "sync:\n  remote: pod-local\n",
		"scratch/notes.txt":  "untracked\n",
	})

	paths, err := dirtyPaths(context.Background(), clone)
	require.NoError(t, err)
	// `scratch/` rather than `scratch/notes.txt`: git collapses a wholly
	// untracked directory to the directory itself, which is the bound that keeps
	// a checkout with a large untracked tree from rendering all of it.
	assert.Equal(t, []string{".beads/config.yaml", "scratch/"}, paths)
}

// TestDirtyPathsOnAPathThatIsNotARepo: the enumeration runs against a checkout
// already known to be in a bad state, so failing is a normal outcome — it must
// report the failure rather than pass a partial list off as a complete one.
func TestDirtyPathsOnAPathThatIsNotARepo(t *testing.T) {
	requireGit(t)

	paths, err := dirtyPaths(context.Background(), t.TempDir())
	require.Error(t, err)
	assert.Empty(t, paths)
}

// TestBlockedDetailSurvivesAFailedEnumeration is the fail-open rule: an
// escalation with no path list is worth far more than no escalation at all, so
// a `git status` that cannot run must not cost the operator the message.
func TestBlockedDetailSurvivesAFailedEnumeration(t *testing.T) {
	requireGit(t)

	detail := blockedFailureDetail(context.Background(), "heimdall", t.TempDir(), &gitError{
		Args:   []string{"fetch", "origin", "main"},
		Stderr: dirtyTreeEvidence,
		Err:    errors.New("exit status 1"),
	})

	assert.Contains(t, detail, "Anvil heimdall")
	assert.Contains(t, detail, "To resolve:")
	assert.NotContains(t, detail, "Blocking paths")
}

// TestBlockedDetailEnumeratesAgainstARealCheckout is the whole feature end to
// end: a blocked scan on a checkout carrying the two known pod-local files
// names them, annotates them, and proposes nothing that would remove them.
func TestBlockedDetailEnumeratesAgainstARealCheckout(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{".beads/config.yaml": "sync:\n  remote: upstream\n"})
	writeFiles(t, clone, map[string]string{".beads/config.yaml": "sync:\n  remote: pod-local\n"})

	detail := blockedFailureDetail(context.Background(), "heimdall", clone, &gitError{
		Args:   []string{"fetch", "origin", "main"},
		Stderr: dirtyTreeEvidence,
		Err:    errors.New("exit status 1"),
	})

	assert.Contains(t, detail, ".beads/config.yaml (pod-local sync.remote override")
	assert.Contains(t, detail, "nothing unexpected is modified")
	assert.Contains(t, detail, "git output: "+dirtyTreeEvidence)
}

// TestEnumerationDoesNotChangeSuppression: the signature is taken from git's
// evidence, never from the rendered detail. A tree whose modified set shifts by
// one file between two runs is the SAME condition, and a signature over the
// detail would re-escalate it nightly — which is the bug the escalation exists
// to fix, arriving through the message that was meant to improve it.
func TestEnumerationDoesNotChangeSuppression(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{"README.md": "seed\n"})
	s, store, events := newTestScanner()
	blocked := &gitError{Args: []string{"fetch"}, Stderr: dirtyTreeEvidence, Err: errors.New("exit status 1")}

	writeFiles(t, clone, map[string]string{"a.go": "package a\n"})
	s.reportScanFailure(context.Background(), "heimdall", clone, blocked)

	writeFiles(t, clone, map[string]string{"b.go": "package b\n"})
	s.reportScanFailure(context.Background(), "heimdall", clone, blocked)

	require.Len(t, events.ofType("depcheck_failed"), 1, "the same condition escalates once even as the tree changes")
	// The row still describes the LATEST observation, which is what makes the
	// refresh worth doing at all.
	assert.Contains(t, store.rows["heimdall"].Detail, "b.go")
}
