package depcheck

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/Robin831/Forge/internal/termtext"
	"github.com/Robin831/Forge/internal/textfmt"
)

// maxBlockingPathsListed bounds the enumerated path list in one escalation.
// The list exists so an operator RECOGNISES the condition at a glance; a
// checkout with two hundred modified files rendered in full is the same wall of
// text the bounded git evidence above it is already kept away from, and it
// would push the remediation command off the end of a Needs Attention row.
const maxBlockingPathsListed = 20

// maxCommandPathsListed bounds the paths written into the remediation command.
// A command is copy-pasted, not read: past a handful of paths an operator works
// from `git status` anyway, and a line that wraps four times reads as noise
// rather than as the one thing to run.
const maxCommandPathsListed = 5

// maxBlockingPathLen bounds one rendered path. Paths come out of a checkout
// Forge did not author, so this is the same treatment the git evidence gets:
// bounded, and stripped of anything a terminal would interpret.
const maxBlockingPathLen = 160

// knownBlockingPath annotates a path an operator will see on a Forge-managed
// anvil that is EXPECTED to differ from upstream. Naming them inline is the
// difference between an escalation an operator recognises in one read and one
// that sends them to inspect a file that is doing exactly what it should.
//
// It is an ordered slice rather than a map so two suffixes that could both
// match one path resolve the same way on every run — a rendered detail is
// compared against the previous one by an operator, and by RecordDepcheckFailure
// when it refreshes the row.
type knownBlockingPath struct {
	// suffix is matched against the whole path or against a trailing path
	// segment boundary, never as a bare substring: `foo.beads/config.yaml` is a
	// different file from `.beads/config.yaml`.
	suffix string
	note   string
}

var knownBlockingPaths = []knownBlockingPath{
	{".beads/config.yaml", "pod-local sync.remote override — expected to differ from upstream, leave it"},
	{".beads/.gitignore", "regenerated by bd — safe to discard"},
}

// blockedCause is what git's words say is holding the scan up. It is derived
// from the SAME text classifyGitFailure already read, but for a different
// question: that one decides whether to escalate at all, this one decides what
// to tell the operator to run. Deriving it here rather than widening
// gitFailureKind keeps that separation — a new remediation is a change to this
// file, and can never change whether a condition is escalated or suppressed.
type blockedCause int

const (
	// causeUnknown is a blocked condition none of the patterns below model. It
	// is the zero value and gets the diagnostic remediation, never a guess.
	causeUnknown blockedCause = iota
	causeDirtyTree
	causeUnmerged
	causeDetachedHead
	causeRefLock
	causeNotARepo
)

// causePatterns map git's own words onto a cause. They are matched lowercased,
// as substrings, in this order — the first match wins, so a message naming both
// an unmerged tree and the modifications it cannot overwrite is reported as the
// merge it is.
//
// Every pattern here is also a blockedPatterns entry (or ErrNoUpstream's
// sentence), because a cause is only ever asked for a failure already
// classified blocked. The reverse does not hold: a blocked pattern with no
// specific remedy — "have diverged" — is deliberately left to causeUnknown
// rather than given an invented command.
var causePatterns = []struct {
	pattern string
	cause   blockedCause
}{
	{"you have unmerged paths", causeUnmerged},
	{"fix conflicts and run", causeUnmerged},
	{"unmerged files", causeUnmerged},
	{"needs merge", causeUnmerged},

	{"local changes to the following files would be overwritten", causeDirtyTree},
	{"would be overwritten by merge", causeDirtyTree},
	{"would be overwritten by checkout", causeDirtyTree},
	{"please commit your changes or stash them", causeDirtyTree},
	{"you have unstaged changes", causeDirtyTree},
	{"your index contains uncommitted changes", causeDirtyTree},
	{"cannot pull with rebase", causeDirtyTree},

	{"you are not currently on a branch", causeDetachedHead},
	{"detached head", causeDetachedHead},
	// ErrNoUpstream's own sentence. A detached HEAD reaches reportScanFailure as
	// that sentinel rather than as git text when resolveUpstream is what failed,
	// and the two are one condition to an operator.
	{"no upstream tracking ref", causeDetachedHead},

	{"cannot lock ref", causeRefLock},
	{"unable to update local ref", causeRefLock},
	{".lock': file exists", causeRefLock},
	{"another git process seems to be running", causeRefLock},
	{"refusing to fetch into branch", causeRefLock},

	{"not a git repository", causeNotARepo},
}

// causeOf reads git's evidence for the specific condition. The argument is the
// already-sanitized evidence string rather than the error, so the cause is
// derived from exactly the text the operator is shown — a remedy naming a
// condition the message does not quote would be unverifiable.
func causeOf(evidence string) blockedCause {
	text := strings.ToLower(evidence)
	for _, c := range causePatterns {
		if strings.Contains(text, c.pattern) {
			return c.cause
		}
	}
	return causeUnknown
}

// involvesWorkingTree reports whether the checkout's own modifications are what
// is blocking. Only then are they enumerated: a detached HEAD or a stale ref
// lock is unaffected by what the tree holds, and listing a pod-local
// `.beads/config.yaml` under "blocking paths" for one of those sends the
// operator after a file that is not the problem.
func (c blockedCause) involvesWorkingTree() bool {
	return c == causeDirtyTree || c == causeUnmerged || c == causeUnknown
}

// dirtyPaths enumerates the working-tree paths that differ from HEAD in
// repoDir, sorted and deduplicated.
//
// It reads `git status --porcelain`, which reports staged, unstaged, untracked
// and unmerged entries in one pass — the four kinds that between them cover
// every tree condition a blocked scan can be sitting on. There is deliberately
// no `git diff --name-only` fallback: that command answers a strict SUBSET of
// this one, so an empty result here means a clean tree rather than a question
// still to be asked.
//
// A wholly untracked directory is reported by git as the directory itself
// rather than as its contents, which is left as-is: it is the bound that keeps a
// checkout with a large untracked tree from rendering every file in it, and a
// directory is exactly as recognisable to an operator and exactly as usable in a
// pathspec.
//
// A failure is returned but is never fatal to the caller: the escalation is
// worth strictly more with the paths in it and is still worth sending without
// them, so blockedFailureDetail degrades to an empty list.
func dirtyPaths(ctx context.Context, repoDir string) ([]string, error) {
	if repoDir == "" {
		return nil, nil
	}
	out, err := runGit(ctx, repoDir, "status", "--porcelain")
	if err != nil {
		return nil, err
	}
	return parsePorcelain(string(out)), nil
}

// parsePorcelain extracts the paths from `git status --porcelain` (v1) output.
//
// Each entry is two status columns, a space, and the path. A rename or copy is
// reported as `ORIG -> NEW`, and the path that matters is NEW: that is the one
// present in the tree and the one a pathspec has to name. A path containing
// anything git considers special arrives C-quoted, which is why the entry is
// unquoted rather than merely trimmed.
func parsePorcelain(out string) []string {
	seen := map[string]struct{}{}
	var paths []string
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimRight(line, "\r")
		// "XY P" is the shortest entry that can carry a path.
		if len(line) < 4 {
			continue
		}
		entry := line[3:]
		if _, dst, ok := strings.Cut(entry, " -> "); ok {
			entry = dst
		}
		p := unquotePorcelainPath(entry)
		if p == "" {
			continue
		}
		if _, dup := seen[p]; dup {
			continue
		}
		seen[p] = struct{}{}
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}

// unquotePorcelainPath undoes git's C-style quoting of a path. git's escapes
// are a subset of Go's string-literal escapes (\n, \t, \", \\ and octal), so
// strconv.Unquote decodes them; a value it refuses is stripped of its quotes and
// used as-is rather than dropped, since a path Forge cannot decode is still a
// path an operator can recognise.
func unquotePorcelainPath(entry string) string {
	s := strings.TrimSpace(entry)
	if len(s) < 2 || !strings.HasPrefix(s, `"`) || !strings.HasSuffix(s, `"`) {
		return s
	}
	if unquoted, err := strconv.Unquote(s); err == nil {
		return unquoted
	}
	return strings.Trim(s, `"`)
}

// safeBlockingPath renders one path for an operator-facing surface. The path
// came out of somebody's checkout, and the detail it lands in is written to
// daemon.log and to an activity-feed row Hearth wraps without stripping, so it
// gets the same treatment as git's own words: escape sequences removed whole,
// line breaks spaced, and a bound on the length.
func safeBlockingPath(p string) string {
	clean := strings.Join(strings.Fields(termtext.Line(p)), " ")
	return textfmt.TruncateRunes(clean, maxBlockingPathLen)
}

// annotateBlockingPath returns the inline explanation for a path an operator is
// expected to see modified, or "" for one they are not.
func annotateBlockingPath(p string) string {
	for _, known := range knownBlockingPaths {
		if p == known.suffix || strings.HasSuffix(p, "/"+known.suffix) {
			return known.note
		}
	}
	return ""
}

// isExpectedBlockingPath reports whether a path is one of the permanently
// modified files a Forge-managed anvil legitimately carries. They are excluded
// from the remediation command: telling an operator to stash the pod-local
// `.beads/config.yaml` is telling them to break the anvil's beads connection.
func isExpectedBlockingPath(p string) bool { return annotateBlockingPath(p) != "" }

// listedPaths is the prefix of the path set the message actually shows. It is
// the one definition of that cap, so a sentence written about "the paths above"
// is written about the paths that are above it.
func listedPaths(paths []string) []string {
	if len(paths) > maxBlockingPathsListed {
		return paths[:maxBlockingPathsListed]
	}
	return paths
}

// renderBlockingPaths renders the enumerated list, annotated, capped, with the
// full count beside it so a truncated list never reads as the whole story.
func renderBlockingPaths(paths []string) string {
	shown := listedPaths(paths)
	extra := len(paths) - len(shown)
	rendered := make([]string, 0, len(shown))
	for _, p := range shown {
		entry := safeBlockingPath(p)
		if note := annotateBlockingPath(p); note != "" {
			entry += " (" + note + ")"
		}
		rendered = append(rendered, entry)
	}
	list := strings.Join(rendered, ", ")
	if extra > 0 {
		list += fmt.Sprintf(", and %d more", extra)
	}
	return list
}

// shellQuotePath renders a path as one shell word. Most paths need no quoting
// at all, which is what keeps the common remediation line readable.
func shellQuotePath(p string) string {
	if p != "" && !strings.ContainsAny(p, " \t\n'\"\\$`&;|<>()*?[]{}#~!") {
		return p
	}
	return "'" + strings.ReplaceAll(p, "'", `'\''`) + "'"
}

// commandPathspec renders the pathspec for the remediation command, or "" when
// no usable one can be built. The second return says whether that pathspec
// covers EVERY path it was handed: past maxCommandPathsListed it does not, and
// the caller must not then describe the command as dealing with the whole set —
// a pasted line that clears five of twelve blocking paths leaves the scan
// blocked while reading like the fix, which is the one way a remediation can be
// worse than none.
//
// A path is only written into a command if sanitization left it BYTE-IDENTICAL:
// a command is meant to be pasted and run, and a path silently truncated or with
// a rune replaced names a different file — or, with the wrong luck, a wider set
// than the operator read. Where that cannot be guaranteed for every path the
// command would carry, the caller falls back to a command with a placeholder,
// which is honest about being a template.
func commandPathspec(paths []string) (string, bool) {
	usable := make([]string, 0, len(paths))
	for _, p := range paths {
		if safeBlockingPath(p) != p {
			return "", false
		}
		usable = append(usable, shellQuotePath(p))
		if len(usable) == maxCommandPathsListed {
			break
		}
	}
	if len(usable) == 0 {
		return "", false
	}
	return strings.Join(usable, " "), len(usable) == len(paths)
}

// unexpectedPaths drops the permanently modified files an anvil is supposed to
// carry, leaving what an operator actually has to deal with.
func unexpectedPaths(paths []string) []string {
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		if !isExpectedBlockingPath(p) {
			out = append(out, p)
		}
	}
	return out
}

// remediation is the one command an operator can run, chosen by cause.
//
// Every command here is recoverable. `stash push` rather than `checkout --`,
// `merge --abort` named alongside "or resolve the conflicts": an escalation is
// read by somebody who has not yet looked at the checkout, and a destructive
// one-liner in that position throws away work the message never claimed to have
// inspected.
func remediation(cause blockedCause, anvil, checkout string, paths []string) string {
	at := checkout
	if at == "" {
		at = "<checkout>"
	}
	switch cause {
	case causeUnmerged:
		return fmt.Sprintf("To resolve: finish the merge in the checkout, or abandon it with `git -C %s merge --abort` "+
			"(`rebase --abort` if it is a rebase).", at)

	case causeDirtyTree:
		unexpected := unexpectedPaths(paths)
		if len(unexpected) == 0 {
			// Everything modified is a file this anvil is meant to carry, so
			// there is nothing to clean up and the blockage is elsewhere in the
			// checkout — say so rather than sending the operator to stash the
			// files that make bd work.
			return fmt.Sprintf("To resolve: nothing unexpected is modified — the paths above are the ones this anvil is "+
				"meant to carry, so inspect the rest of the checkout's git state with `git -C %s status`.", at)
		}
		// The trailing clause is only true when a path the operator can SEE was
		// annotated as expected. Read off the enumerated list rather than off the
		// whole set, since that list is itself capped: an annotation past the cap
		// is one the reader cannot check, so a clause resting on it names a set
		// the message does not contain.
		keep := ""
		if len(unexpectedPaths(listedPaths(paths))) != len(listedPaths(paths)) {
			keep = ", leaving the paths annotated as expected in place"
		}
		spec, whole := commandPathspec(unexpected)
		switch {
		case spec != "" && whole:
			return fmt.Sprintf("To resolve: set the unexpected changes aside (recoverable) with "+
				"`git -C %s stash push -u -- %s`%s.", at, spec, keep)
		case spec != "":
			// More unexpected paths than fit one readable command. The command is
			// still worth pasting, but it is described as the partial step it is
			// and the operator is pointed at the full set — reported as "the
			// unexpected changes" it would read as the whole fix and leave the
			// next scan blocked on the paths it never named.
			return fmt.Sprintf("To resolve: %s are unexpectedly modified, more than fit one command — "+
				"`git -C %s stash push -u -- %s` sets the first %d aside (recoverable)%s; repeat it for the rest, "+
				"which `git -C %s status` lists in full.",
				textfmt.Count(len(unexpected), "path"), at, spec, maxCommandPathsListed, keep, at)
		default:
			return fmt.Sprintf("To resolve: set the unexpected changes aside (recoverable) with "+
				"`git -C %s stash push -u -- <path>` for each of the %s that `git -C %s status` reports and this "+
				"message does not annotate as expected.", at, textfmt.Count(len(unexpected), "path"), at)
		}

	case causeDetachedHead:
		return fmt.Sprintf("To resolve: put the checkout back on a branch that tracks a remote, with "+
			"`git -C %s checkout <branch> && git -C %s branch --set-upstream-to=origin/<branch>`.", at, at)

	case causeRefLock:
		return fmt.Sprintf("To resolve: no git process should be running here — remove the stale lock file git names above "+
			"(under `%s/.git`), then let the next scan retry.", at)

	case causeNotARepo:
		return fmt.Sprintf("To resolve: the registered path is not a git checkout — re-register the anvil against one with "+
			"`forge anvil add %s <path-to-checkout>`.", anvil)

	default:
		return fmt.Sprintf("To resolve: inspect the checkout's git state with `git -C %s status` — Forge has no specific "+
			"remedy modelled for this message.", at)
	}
}

// blockedMessage builds the operator-facing description of a blocked scan.
//
// The order is the point. What is blocked and where comes first, then the paths
// an operator can recognise the condition by, then the one command to run, then
// the sentence saying the entry withdraws itself — and git's raw output LAST,
// under its own label. It used to be the headline, which is exactly backwards:
// git's sentence is evidence for a claim, not the claim, and reading
// "fatal: You are not currently on a branch" as the first thing in a Needs
// Attention row says nothing about which anvil stopped being scanned or what to
// do about it.
//
// gitOut is expected to be already sanitized and bounded (failureEvidence);
// paths are not, and are sanitized here.
func blockedMessage(anvil, checkout string, paths []string, gitOut string) string {
	cause := causeOf(gitOut)

	var b strings.Builder
	fmt.Fprintf(&b, "Anvil %s is not being scanned for dependency updates at all — it is unscanned, not up to date. "+
		"Its manifests cannot be read from the upstream ref, and this repeats identically on every scheduled run "+
		"until the checkout is fixed.", anvil)
	if checkout != "" {
		fmt.Fprintf(&b, " Checkout: %s.", checkout)
	}

	if cause.involvesWorkingTree() && len(paths) > 0 {
		label := "Blocking paths"
		if cause == causeUnknown {
			// Nothing has established that the tree is what is blocking, so the
			// list is context rather than a diagnosis and is labelled as such.
			label = "Working tree"
		}
		fmt.Fprintf(&b, " %s (%s): %s.", label, textfmt.Count(len(paths), "path"), renderBlockingPaths(paths))
	}

	fmt.Fprintf(&b, " %s", remediation(cause, anvil, checkout, paths))
	b.WriteString(" Forge clears this entry automatically once the anvil scans again.")

	if gitOut != "" {
		fmt.Fprintf(&b, " git output: %s", gitOut)
	}
	return b.String()
}
