package depcheck

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/Robin831/Forge/internal/termtext"
	"github.com/Robin831/Forge/internal/textfmt"
)

// maxBlockingPathsListed bounds the enumerated path list in one escalation by
// COUNT. The list exists so an operator RECOGNISES the condition at a glance; a
// checkout with two hundred modified files rendered in full is the same wall of
// text the bounded git evidence below it is already kept away from, and it
// would push the remediation command off the end of a Needs Attention row.
const maxBlockingPathsListed = 20

// maxBlockingPathsBytes bounds the same list by SIZE, and is the binding one on
// deep paths: twenty paths at maxBlockingPathLen each is larger than
// maxFailureDetailBytes, the bound the whole detail is sized in, so a count cap
// alone would let the list overrun the row it is a component of.
const maxBlockingPathsBytes = 400

// maxCommandPathsListed bounds the paths written into the remediation command.
// A command is copy-pasted, not read: past a handful of paths an operator works
// from `git status` anyway, and a line that wraps four times reads as noise
// rather than as the one thing to run.
const maxCommandPathsListed = 5

// maxCommandPathspecBytes is the same bound by size, for the same reason as
// maxBlockingPathsBytes. What it must never do is CUT a path — a truncated one
// names a different file — so commandPathspec stops before the path that would
// cross it and reports how many it covered.
const maxCommandPathspecBytes = 320

// minEvidenceBytes is the floor on git's own words inside the assembled detail.
// The evidence is rendered last and is given whatever maxFailureDetailBytes has
// left, but a message that spent its budget on paths and still shows no evidence
// is unverifiable — the operator cannot check the claim against what git said.
const minEvidenceBytes = 200

// maxBlockingPathLen bounds one rendered path. Paths come out of a checkout
// Forge did not author, so this is the same treatment the git evidence gets:
// bounded, and stripped of anything a terminal would interpret.
const maxBlockingPathLen = 160

// knownBlockingPath annotates a path an operator will see on a Forge-managed
// anvil that is EXPECTED to differ from upstream. Naming them inline is the
// difference between an escalation an operator recognises in one read and one
// that sends them to inspect a file that is doing exactly what it should.
//
// It is an ordered slice rather than a map so two suffixes that could both
// match one path resolve the same way on every run — a rendered detail is
// compared against the previous one by an operator, and by RecordDepcheckFailure
// when it refreshes the row.
type knownBlockingPath struct {
	// suffix is matched against the whole path or against a trailing path
	// segment boundary, never as a bare substring: `foo.beads/config.yaml` is a
	// different file from `.beads/config.yaml`.
	suffix string
	note   string
}

var knownBlockingPaths = []knownBlockingPath{
	{".beads/config.yaml", "pod-local sync.remote override — expected to differ from upstream, leave it"},
	{".beads/.gitignore", "regenerated by bd — safe to discard"},
}

// blockedCause is what git's words say is holding the scan up. It is derived
// from the SAME text classifyGitFailure already read, but for a different
// question: that one decides whether to escalate at all, this one decides what
// to tell the operator to run. Deriving it here rather than widening
// gitFailureKind keeps that separation — a new remediation is a change to this
// file, and can never change whether a condition is escalated or suppressed.
type blockedCause int

const (
	// causeUnknown is a blocked condition none of the patterns below model. It
	// is the zero value and gets the diagnostic remediation, never a guess.
	causeUnknown blockedCause = iota
	causeDirtyTree
	causeUnmerged
	causeDetachedHead
	causeRefLock
	causeNotARepo
)

// causePatterns map git's own words onto a cause. They are matched lowercased,
// as substrings, in this order — the first match wins, so a message naming both
// an unmerged tree and the modifications it cannot overwrite is reported as the
// merge it is.
//
// Every pattern here is also a blockedPatterns entry (or ErrNoUpstream's
// sentence), because a cause is only ever asked for a failure already
// classified blocked. The reverse does not hold: a blocked pattern with no
// specific remedy — "have diverged" — is deliberately left to causeUnknown
// rather than given an invented command.
var causePatterns = []struct {
	pattern string
	cause   blockedCause
}{
	{"you have unmerged paths", causeUnmerged},
	{"fix conflicts and run", causeUnmerged},
	{"unmerged files", causeUnmerged},
	{"needs merge", causeUnmerged},

	{"local changes to the following files would be overwritten", causeDirtyTree},
	{"would be overwritten by merge", causeDirtyTree},
	{"would be overwritten by checkout", causeDirtyTree},
	{"please commit your changes or stash them", causeDirtyTree},
	{"you have unstaged changes", causeDirtyTree},
	{"your index contains uncommitted changes", causeDirtyTree},
	{"cannot pull with rebase", causeDirtyTree},

	{"you are not currently on a branch", causeDetachedHead},
	{"detached head", causeDetachedHead},
	// ErrNoUpstream's own sentence. A detached HEAD reaches reportScanFailure as
	// that sentinel rather than as git text when resolveUpstream is what failed,
	// and the two are one condition to an operator.
	{"no upstream tracking ref", causeDetachedHead},

	{"cannot lock ref", causeRefLock},
	{"unable to update local ref", causeRefLock},
	{".lock': file exists", causeRefLock},
	{"another git process seems to be running", causeRefLock},
	{"refusing to fetch into branch", causeRefLock},

	{"not a git repository", causeNotARepo},
}

// causeOf reads git's evidence for the specific condition. The argument is the
// already-sanitized evidence string rather than the error, so the cause is
// derived from exactly the text the operator is shown — a remedy naming a
// condition the message does not quote would be unverifiable.
func causeOf(evidence string) blockedCause {
	text := strings.ToLower(evidence)
	for _, c := range causePatterns {
		if strings.Contains(text, c.pattern) {
			return c.cause
		}
	}
	return causeUnknown
}

// involvesWorkingTree reports whether the checkout's own modifications are what
// is blocking. Only then are they enumerated: a detached HEAD or a stale ref
// lock is unaffected by what the tree holds, and listing a pod-local
// `.beads/config.yaml` under "blocking paths" for one of those sends the
// operator after a file that is not the problem.
func (c blockedCause) involvesWorkingTree() bool {
	return c == causeDirtyTree || c == causeUnmerged || c == causeUnknown
}

// dirtyPaths enumerates the working-tree paths that differ from HEAD in
// repoDir, sorted and deduplicated.
//
// It reads `git status --porcelain -z`, which reports staged, unstaged,
// untracked and unmerged entries in one pass — the four kinds that between them
// cover every tree condition a blocked scan can be sitting on. There is
// deliberately no `git diff --name-only` fallback: that command answers a strict
// SUBSET of this one, so an empty result here means a clean tree rather than a
// question still to be asked.
//
// `-z` rather than the plain short format because the plain one is ambiguous on
// exactly the paths this package must get right: it C-quotes a path containing a
// space and separates a rename's two paths with ` -> `, which is itself a legal
// substring of a filename, so `notes -> ../secrets.env` and
// `"arrow -> name.txt"` both parse to something that is not a file in the tree —
// and a path that is not a file in the tree is a pathspec that makes the
// remediation command git tells the operator to paste fail outright. Under `-z`
// paths arrive verbatim, NUL-separated, and a rename is two records.
//
// A wholly untracked directory is reported by git as the directory itself
// rather than as its contents, which is left as-is: it is the bound that keeps a
// checkout with a large untracked tree from rendering every file in it, and a
// directory is exactly as recognisable to an operator and exactly as usable in a
// pathspec.
//
// A failure is returned but is never fatal to the caller: the escalation is
// worth strictly more with the paths in it and is still worth sending without
// them, so blockedFailureDetail degrades to an empty list.
func dirtyPaths(ctx context.Context, repoDir string) ([]string, error) {
	if repoDir == "" {
		return nil, nil
	}
	out, err := runGit(ctx, repoDir, "status", "--porcelain", "-z")
	if err != nil {
		return nil, err
	}
	return parsePorcelainZ(string(out)), nil
}

// parsePorcelainZ extracts the paths from `git status --porcelain -z` output.
//
// Each record is two status columns, a space, and the path — unquoted, however
// the path is spelled, because `-z` is the format that has no quoting to undo.
// A rename or copy (`R`/`C` in either column) is TWO records, the current path
// first and the original after it, so the second is consumed here: the path that
// matters is the one present in the tree, which is the one a pathspec has to
// name, and the original no longer exists for a pathspec to match.
func parsePorcelainZ(out string) []string {
	records := strings.Split(out, "\x00")
	seen := map[string]struct{}{}
	var paths []string
	for i := 0; i < len(records); i++ {
		rec := records[i]
		// "XY P" is the shortest record that can carry a path.
		if len(rec) < 4 {
			continue
		}
		if isRenameOrCopy(rec[0]) || isRenameOrCopy(rec[1]) {
			// The original path follows as its own record. Skipping it here is
			// what keeps it from being read as a status entry of its own — its
			// first three bytes are part of a filename, not status columns.
			i++
		}
		p := strings.TrimSpace(rec[3:])
		if p == "" {
			continue
		}
		if _, dup := seen[p]; dup {
			continue
		}
		seen[p] = struct{}{}
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}

// isRenameOrCopy reports whether a porcelain status column says a second,
// original path follows the entry.
func isRenameOrCopy(c byte) bool { return c == 'R' || c == 'C' }

// safeBlockingPath renders one path for an operator-facing surface. The path
// came out of somebody's checkout, and the detail it lands in is written to
// daemon.log and to an activity-feed row Hearth wraps without stripping, so it
// gets the same treatment as git's own words: escape sequences removed whole,
// line breaks spaced, and a bound on the length.
func safeBlockingPath(p string) string {
	clean := strings.Join(strings.Fields(termtext.Line(p)), " ")
	return textfmt.TruncateRunes(clean, maxBlockingPathLen)
}

// annotateBlockingPath returns the inline explanation for a path an operator is
// expected to see modified, or "" for one they are not.
func annotateBlockingPath(p string) string {
	for _, known := range knownBlockingPaths {
		if p == known.suffix || strings.HasSuffix(p, "/"+known.suffix) {
			return known.note
		}
	}
	return ""
}

// expectedPathNames renders the permanently-modified files an anvil legitimately
// carries, for a message that has no enumerated list to annotate. It is read off
// the table rather than written out again, so a new entry there cannot leave one
// sentence naming a set the rest of the file no longer agrees with.
func expectedPathNames() string {
	names := make([]string, 0, len(knownBlockingPaths))
	for _, known := range knownBlockingPaths {
		names = append(names, "`"+known.suffix+"`")
	}
	switch len(names) {
	case 0:
		return "anything this anvil is meant to carry"
	case 1:
		return names[0]
	default:
		return strings.Join(names[:len(names)-1], ", ") + " and " + names[len(names)-1]
	}
}

// isExpectedBlockingPath reports whether a path is one of the permanently
// modified files a Forge-managed anvil legitimately carries. They are excluded
// from the remediation command: telling an operator to stash the pod-local
// `.beads/config.yaml` is telling them to break the anvil's beads connection.
func isExpectedBlockingPath(p string) bool { return annotateBlockingPath(p) != "" }

// renderBlockingPath renders one entry of the enumerated list: the sanitized
// path plus, for one an operator is expected to see modified, the inline note
// saying so.
func renderBlockingPath(p string) string {
	entry := safeBlockingPath(p)
	if note := annotateBlockingPath(p); note != "" {
		entry += " (" + note + ")"
	}
	return entry
}

// listedPaths is the prefix of the path set the message actually shows — both
// caps applied, count and size. It is the one definition of that prefix, so a
// sentence written about "the paths above" is written about the paths that are
// above it, and so the rendered list cannot outgrow the budget listedPaths was
// measured against.
//
// The first path is always listed, whatever it costs: an enumeration block with
// a count and no paths in it says less than no block at all. It cannot overrun
// the budget on its own, since safeBlockingPath bounds one path to
// maxBlockingPathLen bytes and an annotation is one of the fixed notes above.
func listedPaths(paths []string) []string {
	budget := maxBlockingPathsBytes
	for i, p := range paths {
		if i == maxBlockingPathsListed {
			return paths[:i]
		}
		cost := len(renderBlockingPath(p)) + len(", ")
		if i > 0 && cost > budget {
			return paths[:i]
		}
		budget -= cost
	}
	return paths
}

// renderBlockingPaths renders the enumerated list, annotated, capped, with the
// full count beside it so a truncated list never reads as the whole story.
func renderBlockingPaths(paths []string) string {
	shown := listedPaths(paths)
	extra := len(paths) - len(shown)
	rendered := make([]string, 0, len(shown))
	for _, p := range shown {
		rendered = append(rendered, renderBlockingPath(p))
	}
	list := strings.Join(rendered, ", ")
	if extra > 0 {
		list += fmt.Sprintf(", and %d more", extra)
	}
	return list
}

// shellQuotePath renders a path as one shell word. Most paths need no quoting
// at all, which is what keeps the common remediation line readable.
func shellQuotePath(p string) string {
	if p != "" && !strings.ContainsAny(p, " \t\n'\"\\$`&;|<>()*?[]{}#~!") {
		return p
	}
	return "'" + strings.ReplaceAll(p, "'", `'\''`) + "'"
}

// commandPathspec renders the pathspec for the remediation command, or "" when
// no usable one can be built. The second return is how many of the paths it was
// handed that pathspec actually covers: past maxCommandPathsListed (or
// maxCommandPathspecBytes) it is not all of them, and the caller must not then
// describe the command as dealing with the whole set — a pasted line that clears
// five of twelve blocking paths leaves the scan blocked while reading like the
// fix, which is the one way a remediation can be worse than none. It is a count
// rather than a bool because the caller says the number out loud, and two caps
// mean the number is not always maxCommandPathsListed.
//
// A path is only written into a command if sanitization left it BYTE-IDENTICAL:
// a command is meant to be pasted and run, and a path silently truncated or with
// a rune replaced names a different file — or, with the wrong luck, a wider set
// than the operator read. Where that cannot be guaranteed for every path the
// command would carry, the caller falls back to a command with a placeholder,
// which is honest about being a template.
func commandPathspec(paths []string) (string, int) {
	usable := make([]string, 0, len(paths))
	budget := maxCommandPathspecBytes
	for _, p := range paths {
		if safeBlockingPath(p) != p {
			return "", 0
		}
		quoted := shellQuotePath(p)
		// Stop BEFORE the path that would cross the budget rather than cutting
		// it: half a path is a pathspec naming a different file, or none.
		if len(usable) > 0 && len(quoted)+1 > budget {
			break
		}
		budget -= len(quoted) + 1
		usable = append(usable, quoted)
		if len(usable) == maxCommandPathsListed {
			break
		}
	}
	if len(usable) == 0 {
		return "", 0
	}
	return strings.Join(usable, " "), len(usable)
}

// unexpectedPaths drops the permanently modified files an anvil is supposed to
// carry, leaving what an operator actually has to deal with.
func unexpectedPaths(paths []string) []string {
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		if !isExpectedBlockingPath(p) {
			out = append(out, p)
		}
	}
	return out
}

// remediation is the one command an operator can run, chosen by cause.
//
// Every command here is recoverable. `stash push` rather than `checkout --`,
// `merge --abort` named alongside "or resolve the conflicts": an escalation is
// read by somebody who has not yet looked at the checkout, and a destructive
// one-liner in that position throws away work the message never claimed to have
// inspected.
func remediation(cause blockedCause, anvil, checkout string, paths []string) string {
	at := checkout
	if at == "" {
		at = "<checkout>"
	}
	switch cause {
	case causeUnmerged:
		return fmt.Sprintf("To resolve: finish the merge in the checkout, or abandon it with `git -C %s merge --abort` "+
			"(`rebase --abort` if it is a rebase).", at)

	case causeDirtyTree:
		if len(paths) == 0 {
			// Nothing was enumerated: `git status` failed — the likeliest
			// outcome in the checkout an escalation is raised about — or there
			// was no checkout to run it in. Every sentence below is a claim
			// about a set that was inspected, and the "nothing unexpected is
			// modified" one is the worst of them to make here: it tells the
			// operator the checkout is fine while the entry exists precisely
			// because it is not. What a message claims must not outrun what it
			// did, so this says what to look at instead.
			return fmt.Sprintf("To resolve: Forge could not list what is modified here — inspect it with "+
				"`git -C %s status` and set the unexpected changes aside (recoverable) with "+
				"`git -C %s stash push -u -- <path>`, leaving %s in place.", at, at, expectedPathNames())
		}
		unexpected := unexpectedPaths(paths)
		if len(unexpected) == 0 {
			// Everything modified is a file this anvil is meant to carry, so
			// there is nothing to clean up and the blockage is elsewhere in the
			// checkout — say so rather than sending the operator to stash the
			// files that make bd work.
			return fmt.Sprintf("To resolve: nothing unexpected is modified — the paths above are the ones this anvil is "+
				"meant to carry, so inspect the rest of the checkout's git state with `git -C %s status`.", at)
		}
		// The trailing clause is only true when a path the operator can SEE was
		// annotated as expected. Read off the enumerated list rather than off the
		// whole set, since that list is itself capped: an annotation past the cap
		// is one the reader cannot check, so a clause resting on it names a set
		// the message does not contain.
		keep := ""
		if len(unexpectedPaths(listedPaths(paths))) != len(listedPaths(paths)) {
			keep = ", leaving the paths annotated as expected in place"
		}
		spec, covered := commandPathspec(unexpected)
		switch {
		case spec != "" && covered == len(unexpected):
			return fmt.Sprintf("To resolve: set the unexpected changes aside (recoverable) with "+
				"`git -C %s stash push -u -- %s`%s.", at, spec, keep)
		case spec != "":
			// "the first one", not "the first 1": both caps can leave a single
			// path covered — one deep path fills maxCommandPathspecBytes on its
			// own — and a sentence an operator reads aloud has to survive it.
			first := fmt.Sprintf("%d", covered)
			if covered == 1 {
				first = "one"
			}
			// More unexpected paths than fit one readable command. The command is
			// still worth pasting, but it is described as the partial step it is
			// and the operator is pointed at the full set — reported as "the
			// unexpected changes" it would read as the whole fix and leave the
			// next scan blocked on the paths it never named.
			return fmt.Sprintf("To resolve: %s are unexpectedly modified, more than fit one command — "+
				"`git -C %s stash push -u -- %s` sets the first %s aside (recoverable)%s; repeat it for the rest, "+
				"which `git -C %s status` lists in full.",
				textfmt.Count(len(unexpected), "path"), at, spec, first, keep, at)
		default:
			return fmt.Sprintf("To resolve: set the unexpected changes aside (recoverable) with "+
				"`git -C %s stash push -u -- <path>` for each of the %s that `git -C %s status` reports and this "+
				"message does not annotate as expected.", at, textfmt.Count(len(unexpected), "path"), at)
		}

	case causeDetachedHead:
		return fmt.Sprintf("To resolve: put the checkout back on a branch that tracks a remote, with "+
			"`git -C %s checkout <branch> && git -C %s branch --set-upstream-to=origin/<branch>`.", at, at)

	case causeRefLock:
		// "below": git's output is the LAST section of this message, under its
		// own label. Pointing the reader backwards past the headline is what the
		// whole reordering was against.
		return fmt.Sprintf("To resolve: no git process should be running here — remove the stale lock file git names "+
			"below under `git output:` (under `%s/.git`), then let the next scan retry.", at)

	case causeNotARepo:
		// The add is paired with the remove because this only ever fires for an
		// anvil that IS registered — the scan iterates the configured ones — and
		// `forge anvil add` refuses a name that already exists. Named alone it is
		// a command that cannot succeed as written, which leaves the operator
		// exactly where the escalation found them.
		return fmt.Sprintf("To resolve: the registered path is not a git checkout — point the anvil at one, either by "+
			"editing its `path` in `~/.forge/config.yaml` or with "+
			"`forge anvil remove %s && forge anvil add %s <path-to-checkout>`.", anvil, anvil)

	default:
		return fmt.Sprintf("To resolve: inspect the checkout's git state with `git -C %s status` — Forge has no specific "+
			"remedy modelled for this message.", at)
	}
}

// blockedMessage builds the operator-facing description of a blocked scan.
//
// The order is the point. What is blocked and where comes first, then the paths
// an operator can recognise the condition by, then the one command to run, then
// the sentence saying the entry withdraws itself — and git's raw output LAST,
// under its own label. It used to be the headline, which is exactly backwards:
// git's sentence is evidence for a claim, not the claim, and reading
// "fatal: You are not currently on a branch" as the first thing in a Needs
// Attention row says nothing about which anvil stopped being scanned or what to
// do about it.
//
// gitOut is expected to be already sanitized (failureEvidence); paths are not,
// and are sanitized here.
//
// The WHOLE assembled string is what maxFailureDetailBytes sizes — it is
// persisted as one DepcheckFailure.Detail and emitted as one event message — so
// each component is budgeted against it rather than beside it. The path list and
// the remediation's pathspec have their own caps above; git's evidence is
// rendered last and gets what those left, floored at minEvidenceBytes. Trimming
// the evidence rather than the assembled string is the one order that is safe:
// a blind cut of the whole message lands mid-command, and a command truncated to
// a shorter pathspec is a pasted line that names a different set of files.
func blockedMessage(anvil, checkout string, paths []string, gitOut string) string {
	cause := causeOf(gitOut)

	var b strings.Builder
	fmt.Fprintf(&b, "Anvil %s is not being scanned for dependency updates at all — it is unscanned, not up to date. "+
		"Its manifests cannot be read from the upstream ref, and this repeats identically on every scheduled run "+
		"until the checkout is fixed.", anvil)
	if checkout != "" {
		fmt.Fprintf(&b, " Checkout: %s.", checkout)
	}

	if cause.involvesWorkingTree() && len(paths) > 0 {
		label := "Blocking paths"
		if cause == causeUnknown {
			// Nothing has established that the tree is what is blocking, so the
			// list is context rather than a diagnosis and is labelled as such.
			label = "Working tree"
		}
		fmt.Fprintf(&b, " %s (%s): %s.", label, textfmt.Count(len(paths), "path"), renderBlockingPaths(paths))
	}

	fmt.Fprintf(&b, " %s", remediation(cause, anvil, checkout, paths))
	b.WriteString(" Forge clears this entry automatically once the anvil scans again.")

	if gitOut != "" {
		const label = " git output: "
		budget := maxFailureDetailBytes - b.Len() - len(label)
		if budget < minEvidenceBytes {
			budget = minEvidenceBytes
		}
		b.WriteString(label)
		b.WriteString(boundEvidence(gitOut, budget))
	}
	return b.String()
}
