package depcheck

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// dirtyTreeEvidence is git's refusal to touch a tree with local modifications —
// the condition the two known .beads files actually produce.
const dirtyTreeEvidence = "error: Your local changes to the following files would be overwritten by merge: .beads/config.yaml"

// TestBlockedMessageLeadsWithTheAnvilNotWithGit is the bead's headline: git's
// stderr used to BE the message, so a Needs Attention row opened with
// "fatal: ..." and said neither which anvil had stopped being scanned nor what
// to do about it. The evidence is still there — last, under its own label.
func TestBlockedMessageLeadsWithTheAnvilNotWithGit(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, "fatal: You are not currently on a branch.")

	assert.True(t, strings.HasPrefix(msg, "Anvil heimdall"), "the message opens with the anvil, got: %s", msg)
	assert.Contains(t, msg, "/srv/anvils/heimdall")
	assert.Contains(t, msg, "git output: fatal: You are not currently on a branch.")
	assert.Less(t, strings.Index(msg, "To resolve:"), strings.Index(msg, "git output:"),
		"git's own words are secondary — they come after the remediation")
}

// TestBlockedMessageOmitsAnEmptyGitOutput: the label is a promise that evidence
// follows it, so a failure that produced no text must not render an empty one.
func TestBlockedMessageOmitsAnEmptyGitOutput(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, "")

	assert.NotContains(t, msg, "git output:")
	assert.Contains(t, msg, "To resolve:")
}

// TestBlockedMessageAnnotatesTheKnownPaths is why the enumeration is worth
// anything: on a Forge-managed anvil the two paths an operator will most often
// see modified are ones they must NOT clean up, and a bare list of filenames
// says nothing about which is which.
func TestBlockedMessageAnnotatesTheKnownPaths(t *testing.T) {
	paths := []string{".beads/.gitignore", ".beads/config.yaml", "internal/foo.go"}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, "Blocking paths (3 paths)")
	assert.Contains(t, msg, ".beads/config.yaml (pod-local sync.remote override")
	assert.Contains(t, msg, ".beads/.gitignore (regenerated by bd")
	// The unexpected path is the one the remediation acts on; the two expected
	// ones are named in the list and left out of the command.
	assert.Contains(t, msg, "stash push -u -- internal/foo.go`, leaving the paths annotated as expected in place")
	assert.NotContains(t, msg, "stash push -u -- .beads")
}

// TestBlockedMessageWithOnlyExpectedPathsProposesNoCleanup: telling an operator
// to stash the pod-local .beads/config.yaml is telling them to break the
// anvil's beads connection. With nothing else modified there is no cleanup to
// propose and the message must say so instead of inventing one.
func TestBlockedMessageWithOnlyExpectedPathsProposesNoCleanup(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", []string{".beads/config.yaml", ".beads/.gitignore"}, dirtyTreeEvidence)

	assert.Contains(t, msg, "nothing unexpected is modified")
	assert.NotContains(t, msg, "stash push")
}

// TestBlockedMessageCapsThePathList: a checkout with a few hundred modified
// files would otherwise put the whole wall into a persisted row and push the
// remediation off the end of it. The count beside the list stays the full one.
func TestBlockedMessageCapsThePathList(t *testing.T) {
	var paths []string
	for i := 0; i < maxBlockingPathsListed+7; i++ {
		paths = append(paths, fmt.Sprintf("pkg/file%02d.go", i))
	}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, fmt.Sprintf("Blocking paths (%d paths)", len(paths)))
	assert.Contains(t, msg, "and 7 more")
	assert.NotContains(t, msg, "pkg/file20.go", "the 21st path is past the cap")
	// The command is capped harder than the list: a pasted line that wraps four
	// times is not a command an operator runs. What it must NOT do is describe
	// that partial command as dealing with "the unexpected changes" — pasted,
	// it clears five of twenty-seven paths and leaves the scan blocked while
	// reading like the fix.
	assert.Contains(t, msg, "stash push -u -- pkg/file00.go pkg/file01.go pkg/file02.go pkg/file03.go pkg/file04.go`")
	assert.Contains(t, msg, fmt.Sprintf("%d paths are unexpectedly modified, more than fit one command", len(paths)))
	assert.Contains(t, msg, "sets the first 5 aside")
	assert.Contains(t, msg, "repeat it for the rest")
	assert.NotContains(t, msg, "set the unexpected changes aside (recoverable) with `git -C /srv/anvils/heimdall stash push -u -- pkg/file00.go",
		"a command covering 5 of the paths must not be reported as covering the set")
	assert.NotContains(t, msg, "annotated as expected",
		"no path here is annotated as expected, so the message must not name a set the list above does not contain")
}

// TestBlockedMessageCommandCoversTheWholeSetAtTheCap: the boundary between the
// two remediation wordings. At exactly maxCommandPathsListed the pasted command
// IS the whole fix, so it must be reported as one rather than hedged.
func TestBlockedMessageCommandCoversTheWholeSetAtTheCap(t *testing.T) {
	var paths []string
	for i := 0; i < maxCommandPathsListed; i++ {
		paths = append(paths, fmt.Sprintf("pkg/file%02d.go", i))
	}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, "To resolve: set the unexpected changes aside (recoverable) with "+
		"`git -C /srv/anvils/heimdall stash push -u -- pkg/file00.go pkg/file01.go pkg/file02.go pkg/file03.go pkg/file04.go`.")
	assert.NotContains(t, msg, "more than fit one command")
}

// TestBlockedMessageKeepClauseFollowsTheRenderedList: the "leaving the paths
// annotated as expected in place" clause rests on an annotation the operator can
// SEE. An expected path past the list cap is not rendered, so a clause resting on
// it names a set the message does not contain — which reads as a path the render
// dropped.
func TestBlockedMessageKeepClauseFollowsTheRenderedList(t *testing.T) {
	var paths []string
	for i := 0; i < maxBlockingPathsListed; i++ {
		paths = append(paths, fmt.Sprintf("pkg/file%02d.go", i))
	}
	// Sorts last, so it lands past the cap and is never rendered.
	paths = append(paths, "zz/.beads/config.yaml")

	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.NotContains(t, msg, "zz/.beads/config.yaml", "the annotated path is past the list cap")
	assert.NotContains(t, msg, "annotated as expected",
		"the clause must not name an annotation the reader cannot check")
}

// TestBlockedMessageSanitisesPaths: a path comes out of a checkout Forge did not
// author and lands in daemon.log and an activity-feed row Hearth wraps without
// stripping — the same surfaces, and so the same treatment, as git's own words.
func TestBlockedMessageSanitisesPaths(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall",
		[]string{"pkg/\x1b[31mred\x1b[0m.go\nfatal: forged line"}, dirtyTreeEvidence)

	assert.NotContains(t, msg, "\x1b")
	assert.NotContains(t, msg, "\n")
	assert.Contains(t, msg, "pkg/red.go")
	// A path that did not survive sanitization intact is never written into a
	// command: pasted, it would name a different file.
	assert.Contains(t, msg, "stash push -u -- <path>")
}

// TestBlockedMessageOnlyEnumeratesWhenTheTreeIsTheBlocker: a detached HEAD is
// unaffected by what the tree holds, so listing a pod-local .beads/config.yaml
// as a "blocking path" would send the operator after a file that is fine.
func TestBlockedMessageOnlyEnumeratesWhenTheTreeIsTheBlocker(t *testing.T) {
	paths := []string{".beads/config.yaml"}

	detached := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, "fatal: You are not currently on a branch.")
	assert.NotContains(t, detached, "Blocking paths")
	assert.NotContains(t, detached, ".beads/config.yaml")
	assert.Contains(t, detached, "--set-upstream-to=origin/<branch>")

	dirty := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)
	assert.Contains(t, dirty, "Blocking paths")
}

// TestBlockedMessageRemediationPerCause: the command is the operator's whole
// next action, so each modelled condition gets its own — and an unmodelled one
// gets a diagnostic rather than a guess.
func TestBlockedMessageRemediationPerCause(t *testing.T) {
	cases := []struct {
		name     string
		evidence string
		wants    []string
	}{
		{"unmerged", "error: you have unmerged paths.", []string{"merge --abort"}},
		{"detached", "fatal: You are not currently on a branch.", []string{"checkout <branch>", "--set-upstream-to"}},
		{"no upstream", "resolving upstream for /srv/x: no upstream tracking ref", []string{"checkout <branch>"}},
		// "below", because git's output is the LAST section of this message —
		// pointing the reader backwards past the headline is what the reordering
		// this file exists for was against.
		{"ref lock", "error: cannot lock ref 'refs/remotes/origin/main'", []string{
			"stale lock file git names below under `git output:`", "/srv/anvils/heimdall/.git",
		}},
		// The add is paired with the remove: `forge anvil add` refuses a name that
		// already exists, and this escalation only ever fires for an anvil that is
		// registered — so the add alone is a command that cannot succeed.
		{"not a repo", "fatal: not a git repository", []string{
			"forge anvil remove heimdall && forge anvil add heimdall <path-to-checkout>",
			"~/.forge/config.yaml",
		}},
		{"unmodelled", "fatal: refusing to merge unrelated histories", []string{"no specific", "git -C /srv/anvils/heimdall status"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, tc.evidence)
			for _, want := range tc.wants {
				assert.Contains(t, msg, want)
			}
		})
	}
}

// TestBlockedMessageWithoutACheckout: the path is optional at the call site, so
// the command must degrade to a template rather than render `git -C  status`.
func TestBlockedMessageWithoutACheckout(t *testing.T) {
	msg := blockedMessage("heimdall", "", nil, "fatal: You are not currently on a branch.")

	assert.NotContains(t, msg, "Checkout:")
	assert.Contains(t, msg, "git -C <checkout> checkout <branch>")
}

// TestParsePorcelainZ covers the record shapes `git status --porcelain -z`
// produces: staged, unstaged, untracked, unmerged, and a rename — whose CURRENT
// path is the one present in the tree and the one a pathspec has to name, with
// the original following as its own record.
func TestParsePorcelainZ(t *testing.T) {
	out := porcelainZ(
		" M .beads/config.yaml",
		"M  internal/foo.go",
		"?? scratch/notes.txt",
		"UU internal/conflict.go",
		"A  internal/foo.go", // a second entry for one path
		"R  new/name.go", "old/name.go",
	)

	assert.Equal(t, []string{
		".beads/config.yaml",
		"internal/conflict.go",
		"internal/foo.go",
		"new/name.go",
		"scratch/notes.txt",
	}, parsePorcelainZ(out))
}

// TestParsePorcelainZKeepsPathsVerbatim is the reason for -z. The plain short
// format quotes a path with a space in it and separates a rename's two paths
// with ` -> `, which is a legal substring of a filename — so a path containing
// one was cut in half, yielding a name that is not a file in the tree. Under -z
// there is nothing to unquote and nothing to split on.
func TestParsePorcelainZKeepsPathsVerbatim(t *testing.T) {
	assert.Equal(t, []string{"dir/a b.go"}, parsePorcelainZ(porcelainZ(" M dir/a b.go")))
	assert.Equal(t, []string{"dir/é.go"}, parsePorcelainZ(porcelainZ(" M dir/é.go")))
	// A filename containing the rename separator. It is one path, not two, and
	// not a suffix of itself.
	assert.Equal(t, []string{"notes -> ../secrets.env"}, parsePorcelainZ(porcelainZ(" M notes -> ../secrets.env")))
	// A genuine rename whose ORIGINAL path contains the separator: the current
	// path is taken whole and the original record is consumed, never read as a
	// status entry of its own.
	assert.Equal(t, []string{"new.txt"}, parsePorcelainZ(porcelainZ("R  new.txt", "arrow -> old.txt")))
}

// porcelainZ assembles NUL-terminated records the way git writes them.
func porcelainZ(records ...string) string {
	var b strings.Builder
	for _, r := range records {
		b.WriteString(r)
		b.WriteByte(0)
	}
	return b.String()
}

// TestDirtyPathsReadsAnArrowFilenameAsOnePath drives the parse through git
// itself, because the bug it fixes was a claim about a format rather than about
// the code: a path containing " -> " is quoted by the plain short format and was
// cut inside its own quotes, producing `name.txt"` — a path that does not exist,
// so the remediation command naming it fails outright and none of the other,
// correct paths in the same command are set aside either.
func TestDirtyPathsReadsAnArrowFilenameAsOnePath(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{
		"arrow -> name.txt": "seed\n",
		"old.txt":           "seed\n",
	})
	writeFiles(t, clone, map[string]string{"arrow -> name.txt": "modified\n"})
	git(t, clone, "mv", "old.txt", "new.txt")

	paths, err := dirtyPaths(context.Background(), clone)
	require.NoError(t, err)
	assert.Equal(t, []string{"arrow -> name.txt", "new.txt"}, paths)
}

// TestDirtyPathsAgainstARealCheckout drives the enumeration through git itself,
// since the parse is only as good as the format it was written against.
func TestDirtyPathsAgainstARealCheckout(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{
		".beads/config.yaml": "sync:\n  remote: upstream\n",
		"internal/foo.go":    "package internal\n",
	})
	writeFiles(t, clone, map[string]string{
		".beads/config.yaml": "sync:\n  remote: pod-local\n",
		"scratch/notes.txt":  "untracked\n",
	})

	paths, err := dirtyPaths(context.Background(), clone)
	require.NoError(t, err)
	// `scratch/` rather than `scratch/notes.txt`: git collapses a wholly
	// untracked directory to the directory itself, which is the bound that keeps
	// a checkout with a large untracked tree from rendering all of it.
	assert.Equal(t, []string{".beads/config.yaml", "scratch/"}, paths)
}

// TestDirtyPathsOnAPathThatIsNotARepo: the enumeration runs against a checkout
// already known to be in a bad state, so failing is a normal outcome — it must
// report the failure rather than pass a partial list off as a complete one.
func TestDirtyPathsOnAPathThatIsNotARepo(t *testing.T) {
	requireGit(t)

	paths, err := dirtyPaths(context.Background(), t.TempDir())
	require.Error(t, err)
	assert.Empty(t, paths)
}

// TestBlockedDetailSurvivesAFailedEnumeration is the fail-open rule: an
// escalation with no path list is worth far more than no escalation at all, so
// a `git status` that cannot run must not cost the operator the message.
func TestBlockedDetailSurvivesAFailedEnumeration(t *testing.T) {
	requireGit(t)

	detail := blockedFailureDetail(context.Background(), "heimdall", t.TempDir(), &gitError{
		Args:   []string{"fetch", "origin", "main"},
		Stderr: dirtyTreeEvidence,
		Err:    errors.New("exit status 1"),
	})

	assert.Contains(t, detail, "Anvil heimdall")
	assert.Contains(t, detail, "To resolve:")
	assert.NotContains(t, detail, "Blocking paths")
	// And it must not claim the tree is fine. Nothing was enumerated, so
	// "nothing unexpected is modified" would be a statement about a set nobody
	// inspected — and the one statement that tells the operator the checkout is
	// healthy while the entry exists because it is not.
	assert.NotContains(t, detail, "nothing unexpected is modified")
	assert.Contains(t, detail, "could not list what is modified here")
	assert.Contains(t, detail, "`.beads/config.yaml` and `.beads/.gitignore`")
}

// TestBlockedDetailEnumeratesAgainstARealCheckout is the whole feature end to
// end: a blocked scan on a checkout carrying the two known pod-local files
// names them, annotates them, and proposes nothing that would remove them.
func TestBlockedDetailEnumeratesAgainstARealCheckout(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{".beads/config.yaml": "sync:\n  remote: upstream\n"})
	writeFiles(t, clone, map[string]string{".beads/config.yaml": "sync:\n  remote: pod-local\n"})

	detail := blockedFailureDetail(context.Background(), "heimdall", clone, &gitError{
		Args:   []string{"fetch", "origin", "main"},
		Stderr: dirtyTreeEvidence,
		Err:    errors.New("exit status 1"),
	})

	assert.Contains(t, detail, ".beads/config.yaml (pod-local sync.remote override")
	assert.Contains(t, detail, "nothing unexpected is modified")
	assert.Contains(t, detail, "git output: "+dirtyTreeEvidence)
}

// TestEnumerationDoesNotChangeSuppression: the signature is taken from git's
// evidence, never from the rendered detail. A tree whose modified set shifts by
// one file between two runs is the SAME condition, and a signature over the
// detail would re-escalate it nightly — which is the bug the escalation exists
// to fix, arriving through the message that was meant to improve it.
func TestEnumerationDoesNotChangeSuppression(t *testing.T) {
	requireGit(t)

	clone := newOriginAndClone(t, map[string]string{"README.md": "seed\n"})
	s, store, events := newTestScanner()
	blocked := &gitError{Args: []string{"fetch"}, Stderr: dirtyTreeEvidence, Err: errors.New("exit status 1")}

	writeFiles(t, clone, map[string]string{"a.go": "package a\n"})
	s.reportScanFailure(context.Background(), "heimdall", clone, blocked)

	writeFiles(t, clone, map[string]string{"b.go": "package b\n"})
	s.reportScanFailure(context.Background(), "heimdall", clone, blocked)

	require.Len(t, events.ofType("depcheck_failed"), 1, "the same condition escalates once even as the tree changes")
	// The row still describes the LATEST observation, which is what makes the
	// refresh worth doing at all.
	assert.Contains(t, store.rows["heimdall"].Detail, "b.go")
}

// TestDirtyTreeRemediationWithNoEnumeratedPaths is the same rule at the unit
// level, and covers the other route to an empty list: dirtyPaths answers
// `nil, nil` for an empty checkout path. A message may only say the tree holds
// nothing unexpected when a non-empty set was inspected and every member of it
// was annotated.
func TestDirtyTreeRemediationWithNoEnumeratedPaths(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", nil, dirtyTreeEvidence)

	assert.NotContains(t, msg, "nothing unexpected is modified")
	assert.Contains(t, msg, "To resolve: Forge could not list what is modified here")
	assert.Contains(t, msg, "stash push -u -- <path>")
}

// TestBlockedMessageQuotesPathsForTheShell: shellQuotePath is the only thing
// between a path read out of a checkout Forge did not author and a command an
// operator is told to paste. A space, a quote or a shell metacharacter all
// survive sanitization byte-identical, so they ARE written into that command and
// the quoting is load-bearing.
func TestBlockedMessageQuotesPathsForTheShell(t *testing.T) {
	paths := []string{"a b.go", "a'b.go", "x;rm -rf ~"}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.Contains(t, msg, `stash push -u -- 'a b.go' 'a'\''b.go' 'x;rm -rf ~'`+"`")
	// Each is one shell word, so nothing after the first is read as a second
	// argument or as a command of its own.
	assert.NotContains(t, msg, "-- a b.go")
}

// TestBlockedMessageDropsTheCommandForAnOverLongPath is the other side of the
// byte-identity rule, which held only for the escape-sequence case before: a
// path sanitization TRUNCATED names a different file, or a wider set than the
// operator read, so no command may carry it.
func TestBlockedMessageDropsTheCommandForAnOverLongPath(t *testing.T) {
	long := "pkg/" + strings.Repeat("d", maxBlockingPathLen) + "/main.go"
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", []string{long}, dirtyTreeEvidence)

	assert.NotContains(t, msg, "stash push -u -- pkg/")
	assert.Contains(t, msg, "stash push -u -- <path>")
	// The truncated path is still shown: an operator recognises the condition
	// from it even though a command must not name it.
	assert.Contains(t, msg, "pkg/dddd")
}

// TestBlockedMessageLabelsAnUnmodelledTreeAsContext: with no cause established,
// nothing says the tree is what blocks the scan, so the list is context rather
// than a diagnosis — and is labelled as such. Calling it "Blocking paths" would
// be a claim the message has not earned.
func TestBlockedMessageLabelsAnUnmodelledTreeAsContext(t *testing.T) {
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", []string{"internal/foo.go"},
		"fatal: refusing to merge unrelated histories")

	assert.Contains(t, msg, "Working tree (1 path): internal/foo.go")
	assert.NotContains(t, msg, "Blocking paths")
	assert.Contains(t, msg, "no specific")
}

// TestBlockedMessageFitsTheDetailBound: the assembled string is persisted as one
// DepcheckFailure.Detail and emitted as one event message, so
// maxFailureDetailBytes has to bound the WHOLE of it. Bounding each component
// against that number separately adds up to a multiple of it — twenty paths at
// maxBlockingPathLen alone is larger than the budget.
func TestBlockedMessageFitsTheDetailBound(t *testing.T) {
	var paths []string
	for i := 0; i < 200; i++ {
		paths = append(paths, fmt.Sprintf("pkg/%s/file%03d.go", strings.Repeat("deep", 30), i))
	}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths,
		strings.Repeat("error: your local changes to the following files would be overwritten by merge: x ", 200))

	assert.LessOrEqual(t, len(msg), maxFailureDetailBytes, "the whole detail is what the bound sizes")
	// Bounded, not gutted: the parts an operator acts on all survive, and git's
	// own words still appear so the claim can be checked.
	assert.Contains(t, msg, "Anvil heimdall")
	assert.Contains(t, msg, "To resolve:")
	assert.Contains(t, msg, "git output: error:")
	assert.Contains(t, msg, "and 1")
}

// TestBlockedMessageFitsTheBoundWithMultibytePaths: the caps are byte bounds and
// the paths are not ASCII by construction, so a cut through a rune is exactly
// what a per-path bound must not do — and the total must still fit.
func TestBlockedMessageFitsTheBoundWithMultibytePaths(t *testing.T) {
	var paths []string
	for i := 0; i < 50; i++ {
		paths = append(paths, fmt.Sprintf("pkg/%s/fil%03d.go", strings.Repeat("é", 90), i))
	}
	msg := blockedMessage("heimdall", "/srv/anvils/heimdall", paths, dirtyTreeEvidence)

	assert.LessOrEqual(t, len(msg), maxFailureDetailBytes)
	assert.True(t, utf8.ValidString(msg), "a bound applied through a rune leaves a replacement character")
}

// TestCausePatternsAreAllBlockedPatterns pins the invariant the causePatterns
// table documents but nothing enforced: a cause is only ever asked for a failure
// classifyGitError already called blocked, so every pattern here must be one of
// the patterns that classification matches (or ErrNoUpstream's own sentence,
// which reaches the same exit as a sentinel rather than as git text).
//
// The two tables live in different files, and the failure is silent: an edit to
// git's wording in gitfailure.go leaves causeOf falling through to causeUnknown,
// so the condition is still escalated but with the generic `git status` remedy
// and the weaker "Working tree" label instead of the specific one.
func TestCausePatternsAreAllBlockedPatterns(t *testing.T) {
	known := map[string]struct{}{}
	for _, p := range blockedPatterns {
		known[p] = struct{}{}
	}
	known[strings.ToLower(ErrNoUpstream.Error())] = struct{}{}

	for _, c := range causePatterns {
		_, ok := known[c.pattern]
		assert.True(t, ok, "cause pattern %q matches no blockedPatterns entry — causeOf can never see it", c.pattern)
	}
}

// TestBlockedMessageAlwaysShowsSomeEvidence is the floor under the budget. The
// anvil's name and its checkout path are Forge's own config rather than
// something read out of the checkout, so they are never truncated — a `git -C`
// argument cut short names a different directory. A pathological pair of those
// could spend the whole budget before git's words are reached, and a message
// asserting a condition while quoting nothing to check it against is
// unverifiable, so the evidence keeps minEvidenceBytes whatever is left.
func TestBlockedMessageAlwaysShowsSomeEvidence(t *testing.T) {
	checkout := "/srv/anvils/" + strings.Repeat("deep/", 400)
	msg := blockedMessage("heimdall", checkout, nil, strings.Repeat("error: cannot lock ref refs/remotes/origin/main ", 100))

	assert.Contains(t, msg, "git output: error: cannot lock ref")
	assert.GreaterOrEqual(t, len(msg)-strings.Index(msg, "git output: "), minEvidenceBytes)
}
