package github

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Robin831/Forge/internal/vcs"
	"github.com/stretchr/testify/assert"
)

func TestExtractPRNumber(t *testing.T) {
	tests := []struct {
		url      string
		expected int
	}{
		{"https://github.com/Robin831/Forge/pull/123", 123},
		{"https://github.com/owner/repo/pull/1", 1},
		{"invalid", 0},
		{"", 0},
	}

	for _, tt := range tests {
		got := extractPRNumber(tt.url)
		if got != tt.expected {
			t.Errorf("extractPRNumber(%q) = %d; want %d", tt.url, got, tt.expected)
		}
	}
}

func TestParseRepoURL(t *testing.T) {
	tests := []struct {
		url       string
		wantOwner string
		wantRepo  string
		wantErr   bool
	}{
		{"https://github.com/Robin831/Forge", "Robin831", "Forge", false},
		{"https://github.com/Robin831/Forge.git", "Robin831", "Forge", false},
		{"git@github.com:Robin831/Forge.git", "Robin831", "Forge", false},
		{"git@github.com:Robin831/Forge", "Robin831", "Forge", false},
		{"https://github.com/owner/repo/extra", "owner", "repo", false},
		{"invalid", "", "", true},
		{"", "", "", true},
	}

	for _, tt := range tests {
		owner, repo, err := ParseRepoURL(tt.url)
		if (err != nil) != tt.wantErr {
			t.Errorf("ParseRepoURL(%q) error = %v, wantErr %v", tt.url, err, tt.wantErr)
			continue
		}
		if owner != tt.wantOwner || repo != tt.wantRepo {
			t.Errorf("ParseRepoURL(%q) = (%q, %q); want (%q, %q)", tt.url, owner, repo, tt.wantOwner, tt.wantRepo)
		}
	}
}

func TestBuildDefaultBody(t *testing.T) {
	tests := []struct {
		name     string
		params   vcs.CreateParams
		contains []string
		absent   []string
	}{
		{
			name: "full params with type, description, and change summary",
			params: vcs.CreateParams{
				BeadID:          "Forge-abc1",
				Branch:          "forge/Forge-abc1",
				BeadType:        "feature",
				BeadTitle:       "Add widget support",
				BeadDescription: "Users need widget support for the dashboard.",
				ChangeSummary:   "- Added Widget struct\n- Wired up handler",
			},
			contains: []string{
				"## Changes",
				"- Added Widget struct",
				"## Original Issue (feature): Add widget support",
				"Users need widget support for the dashboard.",
				"Bead: Forge-abc1 | Branch: forge/Forge-abc1",
				"Generated by [The Forge]",
			},
		},
		{
			name: "title without type",
			params: vcs.CreateParams{
				BeadID:          "Forge-abc2",
				Branch:          "forge/Forge-abc2",
				BeadTitle:       "Fix login bug",
				BeadDescription: "Login is broken.",
			},
			contains: []string{
				"## Original Issue: Fix login bug",
				"Login is broken.",
				"Bead: Forge-abc2 | Branch: forge/Forge-abc2",
			},
			absent: []string{
				"## Changes",
			},
		},
		{
			name: "no title, no description, no change summary",
			params: vcs.CreateParams{
				BeadID: "Forge-abc3",
				Branch: "forge/Forge-abc3",
			},
			contains: []string{
				"Bead: Forge-abc3 | Branch: forge/Forge-abc3",
				"Generated by [The Forge]",
			},
			absent: []string{
				"## Changes",
				"## Original Issue",
				"## Reviewer's approval notes",
			},
		},
		{
			name: "reviewer notes render under separate heading, never under ## Changes",
			params: vcs.CreateParams{
				BeadID:        "Forge-abc4",
				Branch:        "forge/Forge-abc4",
				ReviewerNotes: "Clean documentation-only lift of Dieter Rams design principles.",
			},
			contains: []string{
				"## Reviewer's approval notes",
				"Clean documentation-only lift",
				"Bead: Forge-abc4 | Branch: forge/Forge-abc4",
			},
			absent: []string{
				"## Changes",
			},
		},
		{
			name: "both change summary and reviewer notes render in their own sections",
			params: vcs.CreateParams{
				BeadID:        "Forge-abc5",
				Branch:        "forge/Forge-abc5",
				ChangeSummary: "- **Widget** - Added widget.",
				ReviewerNotes: "LGTM with minor nits.",
			},
			contains: []string{
				"## Changes",
				"- **Widget** - Added widget.",
				"## Reviewer's approval notes",
				"LGTM with minor nits.",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			body := buildDefaultBody(tt.params)
			for _, want := range tt.contains {
				assert.Contains(t, body, want, "body should contain %q", want)
			}
			for _, unwanted := range tt.absent {
				assert.NotContains(t, body, unwanted, "body should not contain %q", unwanted)
			}
		})
	}

	// Regression for Forge-m1ui + Forge-i1g7: every Forge-authored PR body
	// must include the per-instance forge-managed marker so reconcileOpenPRs
	// does not mistake a contributor's PR (which references a bead but lacks
	// the marker) for one Forge created — and so a sibling Forge instance
	// pointing at the same anvil does not adopt our PR.
	t.Run("forge-managed marker for active instance is always emitted", func(t *testing.T) {
		prev := vcs.ForgeID()
		vcs.SetForgeID("alpha-forge")
		t.Cleanup(func() { vcs.SetForgeID(prev) })

		body := buildDefaultBody(vcs.CreateParams{
			BeadID: "Forge-test",
			Branch: "forge/Forge-test",
		})
		assert.True(t, vcs.IsForgeManagedBy(body, "alpha-forge"),
			"buildDefaultBody must emit the forge-managed marker for the active instance")
		assert.False(t, vcs.IsForgeManagedBy(body, "beta-forge"),
			"buildDefaultBody must NOT emit a marker for a sibling instance")
	})

	// Regression: a warden verdict passed as ReviewerNotes must never appear
	// inside the '## Changes' section. This is the root of the bug the bead
	// was filed for — review-speak leaking under Changes when no changelog
	// fragment is available.
	t.Run("warden verdict never leaks into ## Changes", func(t *testing.T) {
		body := buildDefaultBody(vcs.CreateParams{
			BeadID:        "Forge-leak",
			Branch:        "forge/Forge-leak",
			ReviewerNotes: "Clean documentation-only lift of Dieter Rams design principles.",
		})
		changesIdx := strings.Index(body, "## Changes")
		assert.Equal(t, -1, changesIdx, "no '## Changes' section should be emitted when only ReviewerNotes is set")
		notesIdx := strings.Index(body, "## Reviewer's approval notes")
		assert.NotEqual(t, -1, notesIdx, "reviewer notes heading must be present")
		// The verdict text must live under the reviewer-notes heading, not
		// anywhere above a '## Changes' heading that doesn't exist.
		verdictIdx := strings.Index(body, "Clean documentation-only lift")
		assert.Greater(t, verdictIdx, notesIdx, "verdict text must follow reviewer notes heading")
	})
}

// makeTestRepo creates a temporary git repository with a single commit using
// the given commit message and returns the repo directory.
func makeTestRepo(t *testing.T, commitMsg string) string {
	t.Helper()
	// Unset worktree-specific git env vars so commands run in the temp repo
	// rather than the parent worktree. Restore them after the test.
	for _, key := range []string{"GIT_DIR", "GIT_WORK_TREE", "GIT_CEILING_DIRECTORIES"} {
		if val, ok := os.LookupEnv(key); ok {
			os.Unsetenv(key)
			key, val := key, val
			t.Cleanup(func() { os.Setenv(key, val) })
		}
	}
	dir := t.TempDir()
	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(),
			"GIT_AUTHOR_NAME=Test User",
			"GIT_AUTHOR_EMAIL=test@example.com",
			"GIT_COMMITTER_NAME=Test User",
			"GIT_COMMITTER_EMAIL=test@example.com",
		)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
	run("init", "-b", "main")
	run("config", "user.email", "test@example.com")
	run("config", "user.name", "Test User")
	if err := os.WriteFile(filepath.Join(dir, "file.txt"), []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}
	run("add", ".")
	run("commit", "-m", commitMsg)
	return dir
}

func TestCommitSubject(t *testing.T) {
	dir := makeTestRepo(t, "Add initial file")

	t.Run("branch exists locally", func(t *testing.T) {
		subject := commitSubject(context.Background(), dir, "main")
		assert.Equal(t, "Add initial file", subject)
	})

	t.Run("branch does not exist locally or remotely", func(t *testing.T) {
		subject := commitSubject(context.Background(), dir, "nonexistent-branch-xyz")
		assert.Equal(t, "", subject)
	})
}

func TestSelectTitle(t *testing.T) {
	dir := makeTestRepo(t, "English commit subject")

	t.Run("no title and no bead title gets default forge prefix", func(t *testing.T) {
		p := vcs.CreateParams{BeadID: "Forge-test", WorktreePath: dir, Branch: "nonexistent-branch-xyz"}
		got := selectTitle(context.Background(), p)
		assert.Equal(t, "forge: Forge-test", got)
	})

	t.Run("bead title takes precedence over commit subject", func(t *testing.T) {
		p := vcs.CreateParams{
			BeadID:       "Forge-test",
			Title:        "feat: fix some incidental bug found during implementation",
			BeadTitle:    "Show PR title in Ready to Merge action menu",
			WorktreePath: dir,
			Branch:       "main",
		}
		got := selectTitle(context.Background(), p)
		assert.Equal(t, "Show PR title in Ready to Merge action menu (Forge-test)", got)
	})

	t.Run("commit subject is used as fallback when no bead title is set", func(t *testing.T) {
		p := vcs.CreateParams{
			BeadID:       "Forge-test",
			WorktreePath: dir,
			Branch:       "main",
		}
		got := selectTitle(context.Background(), p)
		assert.Equal(t, "English commit subject (Forge-test)", got)
	})

	t.Run("title with [no-changelog] is preserved unchanged even when bead title is set", func(t *testing.T) {
		originalTitle := "forge: learn rules [no-changelog]"
		p := vcs.CreateParams{
			BeadID:       "Forge-test",
			Title:        originalTitle,
			BeadTitle:    "Auto-learn warden rules",
			WorktreePath: dir,
			Branch:       "main",
		}
		got := selectTitle(context.Background(), p)
		assert.Equal(t, originalTitle, got, "title with [no-changelog] must not be overridden")
	})

	t.Run("non-existent branch with no bead title keeps original title", func(t *testing.T) {
		p := vcs.CreateParams{
			BeadID:       "Forge-test",
			Title:        "Some provided title",
			WorktreePath: dir,
			Branch:       "nonexistent-branch-xyz",
		}
		got := selectTitle(context.Background(), p)
		assert.Equal(t, "Some provided title", got)
	})

	t.Run("crucible parent title with (parent) suffix is preserved when already anchored", func(t *testing.T) {
		p := vcs.CreateParams{
			BeadID:       "Forge-test",
			Title:        "Add widget support (parent) (Forge-test)",
			BeadTitle:    "Add widget support",
			WorktreePath: dir,
			Branch:       "main",
		}
		got := selectTitle(context.Background(), p)
		assert.Equal(t, "Add widget support (parent) (Forge-test)", got,
			"title already anchored to bead ID must not be overwritten by BeadTitle")
	})
}

// TestGitHubCreatePR_AlreadyExistsError verifies that CreatePR errors containing
// "already exists" in stderr are wrapped with vcs.ErrPRAlreadyExists so callers
// can use errors.Is instead of fragile string matching.
func TestGitHubCreatePR_AlreadyExistsError(t *testing.T) {
	tests := []struct {
		name         string
		stderrStr    string
		wantSentinel bool
	}{
		{"already exists message", "a]pull request already exists for this branch", true},
		{"unrelated error", "could not create pull request: permission denied", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Simulate the error wrapping logic from Provider.CreatePR
			var resultErr error
			if strings.Contains(tt.stderrStr, "already exists") {
				resultErr = fmt.Errorf("gh pr create: %w: %s", vcs.ErrPRAlreadyExists, tt.stderrStr)
			} else {
				resultErr = fmt.Errorf("gh pr create failed: %s", tt.stderrStr)
			}

			if tt.wantSentinel {
				assert.True(t, errors.Is(resultErr, vcs.ErrPRAlreadyExists),
					"expected ErrPRAlreadyExists for stderr: %s", tt.stderrStr)
			} else {
				assert.False(t, errors.Is(resultErr, vcs.ErrPRAlreadyExists),
					"did not expect ErrPRAlreadyExists for stderr: %s", tt.stderrStr)
			}
		})
	}
}

func TestProviderImplementsInterface(t *testing.T) {
	// Compile-time check that Provider implements vcs.Provider.
	var _ vcs.Provider = (*Provider)(nil)
}
