package diff

import (
	"fmt"
	"strings"
)

// MaxElidedFilesListed bounds one rendered elided-file list. The point of an
// elided-file note is that the reviewer knows the filter fired and roughly on
// what; a repo-wide regeneration naming two hundred files would re-introduce,
// in filenames, exactly the bloat the filter just removed — and it would do it
// in the prompt the filter exists to protect, ahead of a diff already cut to
// MaxBytes.
const MaxElidedFilesListed = 10

// SafePathList renders a capped, sanitized, comma-separated list of paths
// taken off diff headers, as code spans, with an "and N more" tail for
// whatever the cap dropped.
//
// This is one function rather than one per consumer because it was two: both
// Assay's prompt head and the Warden's diff note name the same list out of the
// same FilterAutoGenerated call, and the Warden's copy borrowed SafePath
// without the cap — so the sanitization and the bound, which are the two halves
// of one treatment, could drift apart on a list neither side chose. The count
// stays the caller's to render: each says "N files elided as generated" or
// "N were omitted" in its own sentence, and that N is always the full length,
// never the capped one.
func SafePathList(files []string) string {
	extra := 0
	if len(files) > MaxElidedFilesListed {
		extra = len(files) - MaxElidedFilesListed
		files = files[:MaxElidedFilesListed]
	}
	names := make([]string, 0, len(files))
	for _, f := range files {
		names = append(names, "`"+SafePath(f)+"`")
	}
	list := strings.Join(names, ", ")
	if extra > 0 {
		list += fmt.Sprintf(", and %d more", extra)
	}
	return list
}
