package diff

import (
	"strings"

	"github.com/bmatcuk/doublestar/v4"
)

// AutoGeneratedPatterns is the default list of glob patterns (doublestar
// syntax) for auto-generated files whose diff hunks are dropped before the
// review. These files are machine-written mirrors of something else — a model,
// a dependency graph — and are not human-reviewable; leaving them in the diff
// either triggers truncation or leads the reviewer to misread the bulk as
// unrelated schema changes and reject on scope drift. For Assay it is also the
// dominant cost in the worst case: every pass prompt embeds the diff, so a
// lockfile in it is paid for once per pass at full cache-write price.
//
// This is the engine's definition of "generated file" and it is the
// authoritative one. A per-anvil assay.skip_paths list is for repo-specific
// noise, not for restating what everybody already means by generated.
//
// The lockfile names are spelled out one by one on purpose, and the shorthand
// that made that necessary was never in this list: it was a per-anvil
// assay.skip_paths that said "**/*.lock" and nothing else. That glob reads like
// it covers lockfiles and covers only the half nobody was worried about.
// yarn.lock, Cargo.lock and Gemfile.lock match it; package-lock.json,
// pnpm-lock.yaml and npm-shrinkwrap.json do not end in ".lock" at all and were
// reviewed in full — and those are the enormous ones. Matching yarn.lock is
// precisely what made the anvil's config look like it was working. One PR paid
// $8.75 to review three package-lock.json files that were 94.9% of its diff
// bytes. "**/*.lock" appears below for the ecosystems that really do use the
// extension; it is the names beside it that make the list correct.
// TestAutoGeneratedPatternsMatchRealNames pins each name against the literal
// filename, so a glob that quietly matches nothing cannot recur.
var AutoGeneratedPatterns = []string{
	// EF Core migration scaffolding. Both are regenerated wholesale by
	// `dotnet ef migrations add`; the migration body beside them
	// (Migrations/<stamp>_Name.cs, no ".Designer") is hand-editable and is
	// deliberately NOT matched.
	"**/Migrations/*.Designer.cs",
	"**/Migrations/*ModelSnapshot.cs",

	// Dependency lockfiles the extension glob below cannot reach. yarn.lock
	// is listed with them even though "**/*.lock" already matches it: the
	// point of this block is to be the readable answer to "is my lockfile
	// filtered", and leaving one name out of it invites the next reader to
	// re-derive the split wrongly, which is how this bug started.
	"**/package-lock.json",
	"**/npm-shrinkwrap.json",
	"**/pnpm-lock.yaml",
	"**/yarn.lock",
	"**/bun.lockb",

	// Cargo.lock, Gemfile.lock, composer.lock, Pipfile.lock, poetry.lock,
	// bun.lock, yarn.lock — the ecosystems that do use the extension.
	"**/*.lock",

	// Built front-end output committed alongside its source. dist/ is the
	// default output directory of Vite, Rollup, esbuild, tsup and Parcel (and
	// of goreleaser and setuptools), and everything under it is regenerated
	// wholesale by the build: a hashed bundle like dist/assets/index-DdoMuon9.js
	// is one 640KB line of minified JavaScript that tokenizes at roughly two
	// characters a token. One such bundle, rebuilt in an otherwise 90KB PR,
	// filled the 250KB diff cap on its own and produced a 165K-token triage
	// prompt whose first turn tripped the per-pass cost ceiling before the
	// pass had read anything. The name-based globs beside it catch the same
	// artifacts when a repo commits them somewhere other than dist/: a
	// minified vendor copy and the source maps a bundler writes next to it.
	"**/dist/**",
	"**/*.min.js",
	"**/*.min.css",
	"**/*.js.map",
	"**/*.css.map",
}

// FilterAutoGenerated drops git-diff hunks whose file path matches any of the
// given doublestar glob patterns. Returns the filtered diff and the list of
// elided file paths (in the order they appeared).
//
// The parser scans for "diff --git " block boundaries using strings.Index so
// it never materialises a []string of all lines — important for multi-MB diffs
// that are processed before the truncation cap is applied. When patterns is
// empty or the input contains no "diff --git" headers, the diff is returned
// unchanged.
func FilterAutoGenerated(diff string, patterns []string) (string, []string) {
	if diff == "" || len(patterns) == 0 {
		return diff, nil
	}

	const marker = "diff --git "
	const sep = "\ndiff --git "

	// Locate the first block header.
	remaining := diff
	var result strings.Builder
	if !strings.HasPrefix(remaining, marker) {
		idx := strings.Index(remaining, sep)
		if idx == -1 {
			return diff, nil // no diff --git headers
		}
		// Preserve any preamble (e.g. a leading commit header) up to and
		// including the newline that precedes the first block.
		result.WriteString(remaining[:idx+1])
		remaining = remaining[idx+1:]
	}

	var elided []string
	for len(remaining) > 0 {
		// remaining always starts with "diff --git " here.
		// Find where the next block begins (the '\n' before "diff --git ").
		nextIdx := strings.Index(remaining[len(marker):], sep)

		var block string
		if nextIdx == -1 {
			block = remaining
			remaining = ""
		} else {
			// nextIdx is relative to remaining[len(marker):].
			// The '\n' separator sits at remaining[len(marker)+nextIdx].
			end := len(marker) + nextIdx + 1 // include the trailing '\n'
			block = remaining[:end]
			remaining = remaining[end:]
		}

		// Inspect only the first line of the block to extract the file path.
		firstNewline := strings.IndexByte(block, '\n')
		headerLine := block
		if firstNewline != -1 {
			headerLine = block[:firstNewline]
		}
		path := ParseGitPath(headerLine)
		if path != "" && MatchesAnyPattern(path, patterns) {
			elided = append(elided, path)
			continue
		}
		result.WriteString(block)
	}
	return result.String(), elided
}

// MatchesAnyPattern returns true when path matches any of the doublestar glob
// patterns. Invalid patterns are skipped silently (they never match) so a bad
// entry cannot accidentally elide every file.
func MatchesAnyPattern(path string, patterns []string) bool {
	for _, p := range patterns {
		ok, err := doublestar.Match(p, path)
		if err != nil {
			continue
		}
		if ok {
			return true
		}
	}
	return false
}
