package diff

import (
	"strings"

	"github.com/bmatcuk/doublestar/v4"
)

// AutoGeneratedPatterns is the default list of glob patterns (doublestar
// syntax) for auto-generated files whose diff hunks are dropped before the
// review. These snapshots mirror the entire model and are not human-reviewable;
// leaving them in the diff either triggers truncation or leads the reviewer to
// misread the bulk as unrelated schema changes and reject on scope drift.
var AutoGeneratedPatterns = []string{
	"**/Migrations/*.Designer.cs",
	"**/Migrations/*ModelSnapshot.cs",
}

// FilterAutoGenerated drops git-diff hunks whose file path matches any of the
// given doublestar glob patterns. Returns the filtered diff and the list of
// elided file paths (in the order they appeared).
//
// The parser scans for "diff --git " block boundaries using strings.Index so
// it never materialises a []string of all lines — important for multi-MB diffs
// that are processed before the truncation cap is applied. When patterns is
// empty or the input contains no "diff --git" headers, the diff is returned
// unchanged.
func FilterAutoGenerated(diff string, patterns []string) (string, []string) {
	if diff == "" || len(patterns) == 0 {
		return diff, nil
	}

	const marker = "diff --git "
	const sep = "\ndiff --git "

	// Locate the first block header.
	remaining := diff
	var result strings.Builder
	if !strings.HasPrefix(remaining, marker) {
		idx := strings.Index(remaining, sep)
		if idx == -1 {
			return diff, nil // no diff --git headers
		}
		// Preserve any preamble (e.g. a leading commit header) up to and
		// including the newline that precedes the first block.
		result.WriteString(remaining[:idx+1])
		remaining = remaining[idx+1:]
	}

	var elided []string
	for len(remaining) > 0 {
		// remaining always starts with "diff --git " here.
		// Find where the next block begins (the '\n' before "diff --git ").
		nextIdx := strings.Index(remaining[len(marker):], sep)

		var block string
		if nextIdx == -1 {
			block = remaining
			remaining = ""
		} else {
			// nextIdx is relative to remaining[len(marker):].
			// The '\n' separator sits at remaining[len(marker)+nextIdx].
			end := len(marker) + nextIdx + 1 // include the trailing '\n'
			block = remaining[:end]
			remaining = remaining[end:]
		}

		// Inspect only the first line of the block to extract the file path.
		firstNewline := strings.IndexByte(block, '\n')
		headerLine := block
		if firstNewline != -1 {
			headerLine = block[:firstNewline]
		}
		path := ParseGitPath(headerLine)
		if path != "" && MatchesAnyPattern(path, patterns) {
			elided = append(elided, path)
			continue
		}
		result.WriteString(block)
	}
	return result.String(), elided
}

// MatchesAnyPattern returns true when path matches any of the doublestar glob
// patterns. Invalid patterns are skipped silently (they never match) so a bad
// entry cannot accidentally elide every file.
func MatchesAnyPattern(path string, patterns []string) bool {
	for _, p := range patterns {
		ok, err := doublestar.Match(p, path)
		if err != nil {
			continue
		}
		if ok {
			return true
		}
	}
	return false
}
