package diff

import (
	"strings"
	"testing"
)

func TestFilterAutoGeneratedFiles_RemovesEFCoreDesignerSnapshot(t *testing.T) {
	designerHunk := strings.Repeat("+// auto-generated snapshot line\n", 4000) // ~120KB
	migrationHunk := "+using Foo.Bar;\n+public partial class AddWidget : Migration {}\n"

	d := "diff --git a/src/Migrations/20260423_AddWidget.Designer.cs b/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"--- a/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"+++ b/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"@@ -1 +1,4000 @@\n" +
		designerHunk +
		"diff --git a/src/Migrations/20260423_AddWidget.cs b/src/Migrations/20260423_AddWidget.cs\n" +
		"--- a/src/Migrations/20260423_AddWidget.cs\n" +
		"+++ b/src/Migrations/20260423_AddWidget.cs\n" +
		"@@ -1 +1,2 @@\n" +
		migrationHunk

	filtered, elided := FilterAutoGenerated(d, AutoGeneratedPatterns)

	if len(elided) != 1 {
		t.Fatalf("expected 1 elided file, got %d: %v", len(elided), elided)
	}
	if elided[0] != "src/Migrations/20260423_AddWidget.Designer.cs" {
		t.Errorf("unexpected elided path: %q", elided[0])
	}
	if strings.Contains(filtered, "auto-generated snapshot line") {
		t.Error("filtered diff should not contain designer snapshot content")
	}
	if !strings.Contains(filtered, "AddWidget : Migration") {
		t.Error("filtered diff should still contain the hand-written migration")
	}
	if len(filtered) >= 50000 {
		t.Errorf("filtered diff should be small after removing designer snapshot; got %d bytes", len(filtered))
	}
}

func TestFilterAutoGeneratedFiles_RemovesModelSnapshot(t *testing.T) {
	d := "diff --git a/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs b/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs\n" +
		"--- a/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs\n" +
		"+++ b/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// snapshot contents\n" +
		"diff --git a/src/Program.cs b/src/Program.cs\n" +
		"--- a/src/Program.cs\n" +
		"+++ b/src/Program.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// real change\n"

	filtered, elided := FilterAutoGenerated(d, AutoGeneratedPatterns)

	if len(elided) != 1 || elided[0] != "src/Data/Migrations/ApplicationDbContextModelSnapshot.cs" {
		t.Errorf("expected ApplicationDbContextModelSnapshot.cs to be elided; got %v", elided)
	}
	if strings.Contains(filtered, "snapshot contents") {
		t.Error("filtered diff should not contain model snapshot content")
	}
	if !strings.Contains(filtered, "real change") {
		t.Error("filtered diff should retain Program.cs hunk")
	}
}

func TestFilterAutoGeneratedFiles_PassthroughWhenNoMatches(t *testing.T) {
	d := "diff --git a/src/Program.cs b/src/Program.cs\n" +
		"--- a/src/Program.cs\n" +
		"+++ b/src/Program.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// change\n"

	filtered, elided := FilterAutoGenerated(d, AutoGeneratedPatterns)

	if len(elided) != 0 {
		t.Errorf("expected no elisions, got %v", elided)
	}
	if filtered != d {
		t.Error("diff should be returned unchanged when no files match")
	}
}

func TestFilterAutoGeneratedFiles_DoesNotMatchDesignerOutsideMigrations(t *testing.T) {
	// A hand-written file named MyDesigner.cs at the repo root must NOT match —
	// the pattern explicitly requires the Migrations/ directory prefix.
	d := "diff --git a/MyDesigner.cs b/MyDesigner.cs\n" +
		"--- a/MyDesigner.cs\n" +
		"+++ b/MyDesigner.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// hand-written\n"

	filtered, elided := FilterAutoGenerated(d, AutoGeneratedPatterns)

	if len(elided) != 0 {
		t.Errorf("hand-written Designer.cs outside Migrations/ should not be elided; got %v", elided)
	}
	if !strings.Contains(filtered, "hand-written") {
		t.Error("filtered diff should retain hand-written file")
	}
}

func TestFilterAutoGeneratedFiles_EmptyInputs(t *testing.T) {
	if out, elided := FilterAutoGenerated("", AutoGeneratedPatterns); out != "" || elided != nil {
		t.Errorf("empty diff should pass through unchanged; got %q, %v", out, elided)
	}
	d := "diff --git a/x b/x\n@@ -0 +1 @@\n+y\n"
	if out, elided := FilterAutoGenerated(d, nil); out != d || elided != nil {
		t.Errorf("nil patterns should pass through unchanged")
	}
}

// TestAutoGeneratedPatternsMatchRealNames pins the default globs against the
// literal filenames the ecosystems actually produce. It exists because the
// class of bug it guards is silent: a glob that matches nothing filters
// nothing, the diff simply stays large, and the only symptom is a review bill.
//
// The lockfile names are verified against the tools' own conventions (npm's
// package-lock.json / npm-shrinkwrap.json, pnpm-lock.yaml, yarn.lock, bun's
// bun.lockb, and the ".lock" family: Cargo, Bundler, Composer, pipenv, poetry).
// The EF Core names are `dotnet ef migrations add` output: a timestamped
// migration body, its "<same-stamp>.Designer.cs" sibling and one
// "<ContextName>ModelSnapshot.cs" per context, all written to the migrations
// output directory — "Migrations" by default, and any parent path when the
// project passes `-o` (matched by the leading "**/"). No .NET anvil is
// registered on this Forge, so those two are pinned by convention here rather
// than against a live checkout; a project that renames the output directory
// itself is deliberately not matched, since only its own migration bodies
// would then be at risk of being elided.
func TestAutoGeneratedPatternsMatchRealNames(t *testing.T) {
	filtered := []string{
		"package-lock.json",
		"client/package-lock.json",
		"docs-site/package-lock.json",
		"apps/web/nested/deep/package-lock.json",
		"npm-shrinkwrap.json",
		"web/npm-shrinkwrap.json",
		"pnpm-lock.yaml",
		"packages/ui/pnpm-lock.yaml",
		"yarn.lock",
		"frontend/yarn.lock",
		"bun.lockb",
		"bun.lock",
		"Cargo.lock",
		"crates/engine/Cargo.lock",
		"Gemfile.lock",
		"composer.lock",
		"Pipfile.lock",
		"poetry.lock",
		"src/Migrations/20260423_AddWidget.Designer.cs",
		"src/Data/Migrations/ApplicationDbContextModelSnapshot.cs",
		"Migrations/AppDbContextModelSnapshot.cs",
	}
	for _, path := range filtered {
		if !MatchesAnyPattern(path, AutoGeneratedPatterns) {
			t.Errorf("%q should be treated as auto-generated but is not", path)
		}
	}

	kept := []string{
		"package.json",
		"pnpm-workspace.yaml",
		"client/package.json",
		"internal/lockfile.go",
		"docs/locking.md",
		"src/locks/Manager.cs",
		"lockfiles/README.md",
		// The migration body beside the Designer file is hand-written.
		"src/Migrations/20260423_AddWidget.cs",
		// A ModelSnapshot outside a Migrations directory is somebody's own
		// type, not EF scaffolding.
		"src/Models/WidgetModelSnapshot.cs",
	}
	for _, path := range kept {
		if MatchesAnyPattern(path, AutoGeneratedPatterns) {
			t.Errorf("%q must stay in the diff but was matched as auto-generated", path)
		}
	}
}

// TestExtensionGlobDoesNotCoverNpmLockfiles is the regression case itself: an
// anvil whose config carried only "**/*.lock" believed it was skipping
// lockfiles and was reviewing most of them in full.
//
// The split is the trap. yarn.lock does end in ".lock" and was filtered, which
// is exactly what made the glob look like it worked — while package-lock.json,
// pnpm-lock.yaml and npm-shrinkwrap.json, the ones that are actually enormous,
// went through untouched. The explicit names are the only reason those three
// are filtered at all.
func TestExtensionGlobDoesNotCoverNpmLockfiles(t *testing.T) {
	extensionOnly := []string{"**/*.lock"}
	for _, path := range []string{
		"package-lock.json",
		"client/package-lock.json",
		"npm-shrinkwrap.json",
		"pnpm-lock.yaml",
	} {
		if MatchesAnyPattern(path, extensionOnly) {
			t.Errorf("%q unexpectedly matched %v; the explicit lockfile globs may no longer be needed", path, extensionOnly)
		}
	}
	// The half that did work, pinned so the asymmetry above stays legible.
	for _, path := range []string{"yarn.lock", "Cargo.lock", "web/Gemfile.lock"} {
		if !MatchesAnyPattern(path, extensionOnly) {
			t.Errorf("%q should still match %v", path, extensionOnly)
		}
	}
}

// TestFilterAutoGeneratedElidesLockfiles walks the shape of the
// PR that motivated the change: three package-lock.json files dwarfing the
// handful of reviewable lines beside them.
func TestFilterAutoGeneratedElidesLockfiles(t *testing.T) {
	lockHunk := strings.Repeat("+        \"resolved\": \"https://registry.npmjs.org/x/-/x-1.0.0.tgz\",\n", 2000)
	block := func(path, body string) string {
		return "diff --git a/" + path + " b/" + path + "\n" +
			"--- a/" + path + "\n+++ b/" + path + "\n@@ -1 +1 @@\n" + body
	}

	d := block("client/package-lock.json", lockHunk) +
		block("docs-site/package-lock.json", lockHunk) +
		block("docs-site-saga/package-lock.json", lockHunk) +
		block("client/package.json", "+    \"lodash\": \"^4.17.21\",\n")

	filtered, elided := FilterAutoGenerated(d, AutoGeneratedPatterns)

	want := []string{
		"client/package-lock.json",
		"docs-site/package-lock.json",
		"docs-site-saga/package-lock.json",
	}
	if len(elided) != len(want) {
		t.Fatalf("expected %d elided files, got %d: %v", len(want), len(elided), elided)
	}
	for i, w := range want {
		if elided[i] != w {
			t.Errorf("elided[%d] = %q, want %q (order must follow the diff)", i, elided[i], w)
		}
	}
	if strings.Contains(filtered, "registry.npmjs.org") {
		t.Error("lockfile content survived the filter")
	}
	if !strings.Contains(filtered, "client/package.json") {
		t.Error("the reviewable package.json change must survive the filter")
	}
	if len(filtered) > len(d)/10 {
		t.Errorf("filtered diff is %d bytes of an original %d; the lockfiles should dominate", len(filtered), len(d))
	}
}
