package depupdate

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os/exec"
	"strings"
	"time"

	"github.com/Robin831/Forge/internal/executil"
)

// CreatePR creates or checks out a batch-update branch, pushes it to origin,
// and opens a single pull request summarising all updated groups for the given
// anvil. It returns the PR URL reported by gh, or an error if any step fails.
//
// The branch name is deps/batch-update-<YYYY-MM-DD> derived from the current
// date. If the branch already exists locally it is checked out rather than
// created anew.
func CreatePR(ctx context.Context, anvilPath, anvilName string, groups []UpdateGroup) (string, error) {
	date := time.Now().Format("2006-01-02")
	branch := "deps/batch-update-" + date

	// git helper: run a git command in anvilPath, return combined stderr on failure.
	git := func(args ...string) error {
		cmd := executil.HideWindow(exec.CommandContext(ctx, "git", args...))
		cmd.Dir = anvilPath
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("git %s: %w\nstderr: %s", strings.Join(args, " "), err, stderr.String())
		}
		return nil
	}

	// Try to create the branch; if it already exists, just check it out.
	if err := git("checkout", "-b", branch); err != nil {
		if err2 := git("checkout", branch); err2 != nil {
			return "", fmt.Errorf("depupdate: checkout branch %q: %w", branch, err2)
		}
	}

	// Push branch and set upstream tracking reference.
	if err := git("push", "--set-upstream", "origin", branch); err != nil {
		return "", fmt.Errorf("depupdate: push branch %q: %w", branch, err)
	}

	title := fmt.Sprintf("chore(deps): batch update %s %s", anvilName, date)
	body := buildPRBody(groups, date)

	ghCtx, ghCancel := context.WithTimeout(ctx, 60*time.Second)
	defer ghCancel()

	cmd := executil.HideWindow(exec.CommandContext(ghCtx, "gh", "pr", "create",
		"--title", title,
		"--body", body,
		"--head", branch,
	))
	cmd.Dir = anvilPath

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		stderrStr := stderr.String()
		if strings.Contains(stderrStr, "already exists") {
			// PR already open for this branch — extract URL from stderr/stdout.
			existing := extractPRURL(stderrStr)
			log.Printf("[depupdate] PR already exists for %s on branch %s: %s", anvilName, branch, existing)
			return existing, nil
		}
		return "", fmt.Errorf("depupdate: gh pr create failed: %w\nstderr: %s", err, stderrStr)
	}

	prURL := strings.TrimSpace(stdout.String())
	log.Printf("[depupdate] Created PR for %s: %s", anvilName, prURL)
	return prURL, nil
}

// buildPRBody constructs a markdown PR description grouped by update kind.
func buildPRBody(groups []UpdateGroup, date string) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "Automated dependency batch update for %s.\n\n", date)

	// Collect groups by kind.
	byKind := map[string][]UpdateGroup{
		"major": {},
		"minor": {},
		"patch": {},
	}
	for _, g := range groups {
		k := g.Kind
		if k != "major" && k != "minor" {
			k = "patch"
		}
		byKind[k] = append(byKind[k], g)
	}

	writeSection := func(heading string, gs []UpdateGroup) {
		if len(gs) == 0 {
			return
		}
		fmt.Fprintf(&sb, "## %s\n\n", heading)
		for _, g := range gs {
			fmt.Fprintf(&sb, "### %s\n\n", g.Name)
			for _, u := range g.Updates {
				fmt.Fprintf(&sb, "- `%s`: %s → %s\n", u.Path, u.Current, u.Latest)
			}
			sb.WriteString("\n")
		}
	}

	writeSection("Major Updates", byKind["major"])
	writeSection("Minor Updates", byKind["minor"])
	writeSection("Patch Updates", byKind["patch"])

	sb.WriteString("---\n_Generated by Forge depupdate._\n")
	return sb.String()
}

// extractPRURL attempts to find a GitHub PR URL in a string (e.g. from gh stderr).
func extractPRURL(s string) string {
	for _, word := range strings.Fields(s) {
		if strings.HasPrefix(word, "https://github.com/") && strings.Contains(word, "/pull/") {
			return strings.TrimRight(word, ".,;")
		}
	}
	return ""
}
