package depupdate

import (
	"strings"
	"testing"
	"time"

	"github.com/Robin831/Forge/internal/depcheck"
)

func TestBranchNameFormat(t *testing.T) {
	date := time.Now().Format("2006-01-02")
	branch := "deps/batch-update-" + date
	if !strings.HasPrefix(branch, "deps/batch-update-") {
		t.Errorf("branch name %q does not start with deps/batch-update-", branch)
	}
	// Verify the date portion looks like YYYY-MM-DD.
	suffix := strings.TrimPrefix(branch, "deps/batch-update-")
	parts := strings.Split(suffix, "-")
	if len(parts) != 3 {
		t.Errorf("expected date portion YYYY-MM-DD, got %q", suffix)
	}
}

func TestBuildPRBody_Title(t *testing.T) {
	groups := []UpdateGroup{
		{
			Name:    "lodash",
			Updates: []depcheck.ModuleUpdate{{Path: "lodash", Current: "4.17.20", Latest: "4.17.21"}},
			Kind:    "patch",
		},
		{
			Name:    "react",
			Updates: []depcheck.ModuleUpdate{{Path: "react", Current: "17.0.0", Latest: "18.0.0"}},
			Kind:    "major",
		},
	}

	body := buildPRBody(groups, "2026-03-21")

	if !strings.Contains(body, "2026-03-21") {
		t.Error("body should contain the date")
	}
	if !strings.Contains(body, "## Major Updates") {
		t.Error("body should contain Major Updates section")
	}
	if !strings.Contains(body, "## Patch Updates") {
		t.Error("body should contain Patch Updates section")
	}
	if strings.Contains(body, "## Minor Updates") {
		t.Error("body should NOT contain Minor Updates section when there are none")
	}
	if !strings.Contains(body, "`lodash`: 4.17.20 → 4.17.21") {
		t.Error("body should contain lodash update line")
	}
	if !strings.Contains(body, "`react`: 17.0.0 → 18.0.0") {
		t.Error("body should contain react update line")
	}
	if !strings.Contains(body, "Generated by Forge depupdate") {
		t.Error("body should contain footer attribution")
	}
}

func TestBuildPRBody_AllKinds(t *testing.T) {
	groups := []UpdateGroup{
		{Name: "g1", Updates: []depcheck.ModuleUpdate{{Path: "a", Current: "1.0.0", Latest: "1.0.1"}}, Kind: "patch"},
		{Name: "g2", Updates: []depcheck.ModuleUpdate{{Path: "b", Current: "1.0.0", Latest: "1.1.0"}}, Kind: "minor"},
		{Name: "g3", Updates: []depcheck.ModuleUpdate{{Path: "c", Current: "1.0.0", Latest: "2.0.0"}}, Kind: "major"},
	}
	body := buildPRBody(groups, "2026-03-21")

	for _, section := range []string{"## Major Updates", "## Minor Updates", "## Patch Updates"} {
		if !strings.Contains(body, section) {
			t.Errorf("body missing section %q", section)
		}
	}
}

func TestBuildPRBody_EmptyGroups(t *testing.T) {
	body := buildPRBody(nil, "2026-03-21")
	// Should still produce a valid (if minimal) body.
	if !strings.Contains(body, "2026-03-21") {
		t.Error("body should contain the date even with no groups")
	}
}

func TestExtractPRURL(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{
			input: "A pull request already exists: https://github.com/org/repo/pull/42",
			want:  "https://github.com/org/repo/pull/42",
		},
		{
			input: "error: nothing found",
			want:  "",
		},
		{
			input: "see https://github.com/org/repo/pull/100.",
			want:  "https://github.com/org/repo/pull/100",
		},
	}
	for _, tt := range tests {
		got := extractPRURL(tt.input)
		if got != tt.want {
			t.Errorf("extractPRURL(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
