#!/bin/bash
# restart.sh — Source-of-truth for the Forge daemon rebuild/restart script.
#
# Deployed to ~/.forge/restart.sh on the production host. Hytte's Mezzanine
# "Rebuild & Restart" button POSTs to /api/forge/restart, which shells out to
# this script via RestartForgeHandler.
#
# The running daemon continuously rewrites .beads/issues.jsonl in its working
# tree (bd auto-export), so a plain `git pull` always trips
# "local changes would be overwritten by merge" and aborts. We mirror the
# same stash-before-pull / drop-after pattern used in the Hytte deploy
# workflow: the JSONL is regenerated by bd on the next write, so discarding
# the stash is safe.

set -e

echo "==> Pulling latest..."
cd ~/source/Forge

# Self-heal: the running daemon re-sets core.worktree on every worker spawn,
# leaving the main repo in a "fatal: this operation must be run in a work tree"
# state. Unset it before pulling. Once the new binary is live (Forge-d6j5 fix),
# this is redundant but harmless.
git config --unset core.worktree 2>/dev/null || true

if ! git diff --quiet || ! git diff --cached --quiet; then
  git stash push -m "restart-auto-stash-$(date +%s)"
  STASHED=1
else
  STASHED=0
fi
git pull --ff-only origin main
if [ "$STASHED" = "1" ]; then
  git stash drop || true
fi

echo "==> Building..."
go build -o ~/bin/forge ./cmd/forge

echo "==> Restarting daemon..."
sudo systemctl restart forge

echo "==> Done. Status:"
sudo systemctl status forge --no-pager -l | head -10
