package assay

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/Robin831/Forge/internal/config"
	"github.com/Robin831/Forge/internal/diff"
	"github.com/Robin831/Forge/internal/provider"
)

// Config is the resolved configuration the Assay review engine needs for a
// single review. It is deliberately decoupled from config.AssayConfig (the
// on-disk YAML shape) so the engine can be exercised in tests without loading
// real configuration. Build one from a config.AssayConfig via FromAssayConfig,
// or construct it directly in tests.
//
// IMPORTANT: every model identifier consumed by the engine comes from
// ModelTier or the TriageModel/ReviewModel hints — the package NEVER hard-codes
// a concrete model ID. When a model hint is empty the underlying provider
// chooses its own default model.
type Config struct {
	// ModelTier is a semantic label describing the desired model strength
	// (e.g. "default", "fast"). It is recorded for observability and may be
	// surfaced to operators; the concrete model identifiers are always the
	// TriageModel/ReviewModel hints below, never a literal baked into the code.
	ModelTier string

	// TriageProvider and ReviewProvider are the LEGACY provider specs (the same
	// syntax as settings.providers, e.g. "claude", "gemini/gemini-2.5-pro").
	// TriageProvider drives the cheap scoping pass; ReviewProvider drives the
	// five deep passes. They are step 5 of the per-pass resolution in
	// providersFor, below every assay stage_providers key: a pass whose stage
	// key is set never reads them.
	TriageProvider string
	ReviewProvider string

	// TriageModel and ReviewModel are model hints (provider-specific model
	// identifiers) used for the triage pass and the deep passes respectively.
	// Empty means "let the provider pick its default model".
	TriageModel string
	ReviewModel string

	// AnvilStageProviders and GlobalStageProviders are the anvil's own
	// stage_providers map and settings.stage_providers, handed in whole so the
	// engine resolves each pass from the same maps doctor and the cost tables
	// read (see ForAnvil). Only the "assay" and "assay.<pass>" keys are ever
	// consulted: an Assay pass never inherits the smith chain or
	// settings.providers, since a review model chosen for implementation work
	// is a choice nobody made for review.
	AnvilStageProviders  map[string][]string
	GlobalStageProviders map[string][]string

	// NitCap caps the number of Nit-severity findings retained after
	// aggregation. Values <= 0 mean "no cap". The cap is cumulative per PR:
	// Nits still open from earlier reviews count against it, so a repeat
	// review cannot add another NitCap on top of the last run's.
	NitCap int

	// MaxFindingsPerPR caps the cumulative number of findings — every
	// severity, Important included — a PR may accumulate across all of its
	// reviews. Findings still open from earlier runs count against it. It is
	// the hard brake on total comment volume; values <= 0 mean "no cap".
	MaxFindingsPerPR int

	// ShadowMode, when true, signals that the review must not produce public
	// side effects: Review still writes findings to pr_findings, but the caller
	// must not post them. Defaults to the safe value (true) via FromAssayConfig.
	ShadowMode bool

	// MaxDiffBytes caps the size of the diff embedded in pass prompts. Values
	// <= 0 fall back to diff.MaxBytes.
	MaxDiffBytes int

	// MaxTurnsPerPass bounds each pass agent session. Values <= 0 fall back
	// to the engine default (assayMaxTurns).
	MaxTurnsPerPass int

	// MaxCostPerPassUSD bounds the estimated spend of a single pass session.
	// The runner accumulates the session's cost as its turns complete and
	// stops the pass the moment it reaches this value, reporting
	// ReasonMaxCost. Zero disables the ceiling, which is what every
	// configuration did before it existed; newCostTracker normalises anything
	// else unusable (a negative, NaN, Inf) to the same disabled state, though
	// config validation rejects a negative before it can get this far.
	//
	// It bounds a session, not a run: five deep passes each hold their own
	// budget, and a pass that is stopped costs the run its coverage rather
	// than the run itself (the result comes back partial, naming the pass).
	MaxCostPerPassUSD float64

	// SkipPaths are doublestar globs whose files are excluded from review
	// (their hunks are dropped before the diff reaches any pass).
	SkipPaths []string

	// AutoGeneratedPatterns are doublestar globs whose hunks are filtered out
	// before review (machine-generated snapshots, etc.). Empty uses
	// diff.AutoGeneratedPatterns.
	AutoGeneratedPatterns []string

	// primerWaitOverride replaces primerWaitDefault as the bound on how long
	// the deep-pass fan-out waits for the primer to start answering. Unset
	// (zero) uses the default; a negative value disables the stagger entirely
	// and launches all five passes at once, which is what the pre-Forge-1v68
	// behaviour was. It is unexported because it is a test seam and a
	// break-glass, not a knob an anvil should be tuning: the value that matters
	// is a normal time-to-first-token, and it is the same everywhere.
	primerWaitOverride time.Duration

	// runner is the seam used to invoke a model for a single pass. When nil,
	// Review installs the default Smith-based runner. Tests in this package set
	// it directly (or via WithRunner) to a deterministic stub so no real model
	// process is spawned.
	runner PassRunner
}

// DefaultConfig returns a Config with conservative defaults: shadow mode on,
// no model hints (providers pick their own defaults), and the shared diff
// auto-generated filters.
func DefaultConfig() Config {
	return Config{
		ModelTier:             "default",
		ShadowMode:            true,
		NitCap:                0,
		MaxDiffBytes:          diff.MaxBytes,
		AutoGeneratedPatterns: diff.AutoGeneratedPatterns,
	}
}

// FromAssayConfig builds an engine Config from the resolved on-disk Assay
// configuration. Unset fields inherit the DefaultConfig values so the engine
// always has a usable configuration.
func FromAssayConfig(ac config.AssayConfig) Config {
	cfg := DefaultConfig()
	cfg.ShadowMode = ac.IsShadowMode()
	cfg.NitCap = ac.GetNitCap()
	cfg.MaxFindingsPerPR = ac.GetMaxFindingsPerPR()
	if ac.ModelTier != "" {
		cfg.ModelTier = ac.ModelTier
	}
	cfg.TriageProvider = ac.TriageProvider
	cfg.ReviewProvider = ac.ReviewProvider
	cfg.TriageModel = ac.TriageModel
	cfg.ReviewModel = ac.ReviewModel
	if mdb := ac.GetMaxDiffBytes(); mdb > 0 {
		cfg.MaxDiffBytes = mdb
	}
	if mt := ac.GetMaxTurnsPerPass(); mt > 0 {
		cfg.MaxTurnsPerPass = mt
	}
	// Read unconditionally, unlike the fields above: 0 is a meaningful value
	// here (the ceiling off), so a "> 0" guard would make it impossible to
	// turn off a default that is on.
	cfg.MaxCostPerPassUSD = ac.GetMaxCostPerPassUSD()
	if len(ac.SkipPaths) > 0 {
		cfg.SkipPaths = ac.SkipPaths
	}
	return cfg
}

// ForAnvil builds the engine Config for one anvil: the anvil's resolved assay
// block (overlay over global) plus the two stage_providers maps the per-pass
// provider resolution reads. It is the one constructor the daemon and doctor
// share, so the provider a review runs on and the provider doctor reports for
// it cannot come from two derivations. An anvil name the config does not know
// resolves against the global configuration alone.
func ForAnvil(cfg *config.Config, anvil string) Config {
	if cfg == nil {
		return DefaultConfig()
	}
	c := FromAssayConfig(cfg.ResolvedAssay(anvil))
	c.GlobalStageProviders = cfg.Settings.StageProviders
	if a, ok := cfg.Anvils[anvil]; ok {
		c.AnvilStageProviders = a.StageProviders
	}
	return c
}

// WithRunner returns a copy of the Config with the given pass runner installed.
// External callers use this to inject a custom runner; the package's own tests
// may set the unexported field directly.
func (c Config) WithRunner(r PassRunner) Config {
	c.runner = r
	return c
}

// primerWait returns how long the fan-out waits for the primer pass to reach
// its first answered token before releasing the other deep passes anyway.
func (c Config) primerWait() time.Duration {
	if c.primerWaitOverride != 0 {
		return c.primerWaitOverride
	}
	return primerWaitDefault
}

// maxDiffBytes returns the effective diff size cap, applying the diff.MaxBytes
// default when unset.
func (c Config) maxDiffBytes() int {
	if c.MaxDiffBytes <= 0 {
		return diff.MaxBytes
	}
	return c.MaxDiffBytes
}

// autoGenPatterns returns the effective auto-generated file patterns, applying
// the shared default when unset.
func (c Config) autoGenPatterns() []string {
	if len(c.AutoGeneratedPatterns) == 0 {
		return diff.AutoGeneratedPatterns
	}
	return c.AutoGeneratedPatterns
}

// ProviderSource names which precedence step supplied a pass's provider chain.
type ProviderSource int

// The six steps of providersFor, in precedence order.
const (
	SourceAnvilPassStage ProviderSource = iota + 1
	SourceAnvilAssayStage
	SourceGlobalPassStage
	SourceGlobalAssayStage
	SourceLegacyAssayBlock
	SourceProviderDefaults
)

// assayStageKey is the stage_providers key every Assay pass falls back to.
const assayStageKey = "assay"

// passStageKey is the per-pass stage_providers key, e.g. "assay.logic".
func passStageKey(pass string) string { return assayStageKey + "." + pass }

// ResolvedChain is one pass's provider chain and the step that supplied it.
type ResolvedChain struct {
	// Pass is the pass identifier ("triage", "logic", …).
	Pass string
	// Providers is the ordered chain as configured. It is never empty. The
	// head is what a pass spawns first; the entries after it are rate-limit
	// fallbacks, tried in order for that pass alone (see runDeepPass).
	Providers []provider.Provider
	// Source is the precedence step the chain came from.
	Source ProviderSource
	// Key is the stage_providers key (steps 1-4) or the legacy assay keys
	// (step 5) that supplied the chain; empty for provider defaults.
	Key string
}

// SourceLabel renders where the chain came from for doctor and the conflict
// warning: "anvil stage_providers[assay.logic]", "assay.review_provider+
// assay.review_model", "provider defaults".
func (r ResolvedChain) SourceLabel() string {
	switch r.Source {
	case SourceAnvilPassStage, SourceAnvilAssayStage:
		return "anvil stage_providers[" + r.Key + "]"
	case SourceGlobalPassStage, SourceGlobalAssayStage:
		return "settings.stage_providers[" + r.Key + "]"
	case SourceLegacyAssayBlock:
		return r.Key
	default:
		return "provider defaults"
	}
}

// Fallbacks returns the chain entries after the head: the providers a pass
// moves to, in order, when the entry before is rate limited.
func (r ResolvedChain) Fallbacks() []provider.Provider {
	if len(r.Providers) <= 1 {
		return nil
	}
	return r.Providers[1:]
}

// ChainLabel renders the chain as "claude/claude-opus-5 -> gemini".
func (r ResolvedChain) ChainLabel() string {
	parts := make([]string, 0, len(r.Providers))
	for _, p := range r.Providers {
		parts = append(parts, p.Label())
	}
	return strings.Join(parts, " -> ")
}

// providersFor resolves the provider chain for one pass. The order is:
//
//  1. the anvil's stage_providers["assay.<pass>"]
//  2. the anvil's stage_providers["assay"]
//  3. settings.stage_providers["assay.<pass>"]
//  4. settings.stage_providers["assay"]
//  5. the legacy assay block (overlay already folded over global by
//     config.ResolvedAssay): triage_provider/triage_model for triage, falling
//     back to review_provider/review_model exactly as it always did, and
//     review_provider/review_model for every deep pass
//  6. the head of provider.Defaults
//
// The value is a rate-limit fallback chain exactly as it is for every other
// stage: a pass starts on the head and moves to the next entry only when the
// one before it is rate limited (runDeepPass, runTriage). Each pass walks its
// own chain, so a failover on one pass never moves another.
//
// Anvil scope outranks pass specificity: an anvil's "assay" beats a global
// "assay.logic", because an anvil override is a statement about this
// repository and a global per-pass key is a statement about every repository.
// smith_providers and settings.providers are never read — see
// AnvilStageProviders.
func (c Config) providersFor(pass string) []provider.Provider {
	return c.resolveChain(pass).Providers
}

// providerFor is the head of a pass's chain: the provider its first session
// spawns, and the one a runner called outside the chain walk uses. The model
// is taken exclusively from configuration (a stage spec's "/model" suffix or
// the legacy hints), never hard-coded; an unset model leaves Provider.Model
// empty so the provider uses its own default.
func (c Config) providerFor(pass string) provider.Provider {
	return c.providersFor(pass)[0]
}

func (c Config) resolveChain(pass string) ResolvedChain {
	steps := []struct {
		m   map[string][]string
		key string
		src ProviderSource
	}{
		{c.AnvilStageProviders, passStageKey(pass), SourceAnvilPassStage},
		{c.AnvilStageProviders, assayStageKey, SourceAnvilAssayStage},
		{c.GlobalStageProviders, passStageKey(pass), SourceGlobalPassStage},
		{c.GlobalStageProviders, assayStageKey, SourceGlobalAssayStage},
	}
	for _, st := range steps {
		if chain := stageChain(st.m, st.key); len(chain) > 0 {
			return ResolvedChain{Pass: pass, Providers: chain, Source: st.src, Key: st.key}
		}
	}
	if pv, key, ok := c.legacyProvider(pass); ok {
		return ResolvedChain{Pass: pass, Providers: []provider.Provider{pv}, Source: SourceLegacyAssayBlock, Key: key}
	}
	// Only the default chain's head: a config that asked for nothing gets no
	// fallback, rather than one inherited from the global defaults that nobody
	// chose for review.
	return ResolvedChain{Pass: pass, Providers: provider.Defaults()[:1], Source: SourceProviderDefaults}
}

// stageChain parses one stage_providers entry. An absent key, an empty list and
// a list of blank specs all read as unset, so resolution moves on to the next
// step rather than returning a chain with nothing in it.
func stageChain(m map[string][]string, key string) []provider.Provider {
	specs, ok := m[key]
	if !ok || len(specs) == 0 {
		return nil
	}
	return provider.FromConfig(specs)
}

// legacyProvider applies the legacy assay block for a pass, reporting false
// when none of the keys that pass reads is set. The triage fallback to the
// review keys is today's behaviour and is kept byte-for-byte: an anvil that
// set only review_model has always run triage on that model too.
func (c Config) legacyProvider(pass string) (provider.Provider, string, bool) {
	spec, model := c.ReviewProvider, c.ReviewModel
	var keys []string
	if pass == passTriage.Name {
		if c.TriageProvider != "" {
			spec = c.TriageProvider
			keys = append(keys, "assay.triage_provider")
		} else if spec != "" {
			keys = append(keys, "assay.review_provider")
		}
		if c.TriageModel != "" {
			model = c.TriageModel
			keys = append(keys, "assay.triage_model")
		} else if model != "" {
			keys = append(keys, "assay.review_model")
		}
	} else {
		if spec != "" {
			keys = append(keys, "assay.review_provider")
		}
		if model != "" {
			keys = append(keys, "assay.review_model")
		}
	}
	if spec == "" && model == "" {
		return provider.Provider{}, "", false
	}
	pv := provider.Provider{Kind: provider.Claude}
	if spec != "" {
		if list := provider.FromConfig([]string{spec}); len(list) > 0 {
			pv = list[0]
		}
	}
	if model != "" {
		pv.Model = model
	}
	return pv, strings.Join(keys, "+"), true
}

// PassNames returns every Assay pass identifier in run order: triage first,
// then the five deep passes.
func PassNames() []string {
	out := make([]string, 0, 1+len(deepPasses))
	out = append(out, passTriage.Name)
	for _, p := range deepPasses {
		out = append(out, p.Name)
	}
	return out
}

// ResolvedChains returns every pass's resolved chain, in PassNames order.
func (c Config) ResolvedChains() []ResolvedChain {
	names := PassNames()
	out := make([]ResolvedChain, 0, len(names))
	for _, n := range names {
		out = append(out, c.resolveChain(n))
	}
	return out
}

// LegacyStageConflict is an anvil that sets both a legacy assay provider/model
// key and an assay stage_providers key. Both are valid on their own; together
// they read as two answers to one question, so the daemon names which one
// actually decides each pass.
type LegacyStageConflict struct {
	Anvil string
	// LegacyKeys are the legacy assay keys set for the anvil (overlay or global).
	LegacyKeys []string
	// StageKeys are the assay stage_providers keys in scope, qualified by
	// where they are set ("anvil:assay.logic", "settings:assay").
	StageKeys []string
	// StageWins and LegacyWins partition the passes by which one decides them.
	StageWins  []string
	LegacyWins []string
}

// String renders the one log line the warning is.
func (lc LegacyStageConflict) String() string {
	msg := fmt.Sprintf("anvil %s sets legacy assay keys [%s] and stage_providers keys [%s]; stage_providers wins",
		lc.Anvil, strings.Join(lc.LegacyKeys, ", "), strings.Join(lc.StageKeys, ", "))
	if len(lc.StageWins) > 0 {
		msg += " for " + strings.Join(lc.StageWins, ", ")
	}
	if len(lc.LegacyWins) > 0 {
		msg += "; legacy keys still decide " + strings.Join(lc.LegacyWins, ", ")
	}
	return msg
}

// LegacyStageConflicts reports every Assay-enabled anvil on which a legacy
// assay provider/model key and an assay stage_providers key are both set, in
// anvil-name order.
func LegacyStageConflicts(cfg *config.Config) []LegacyStageConflict {
	if cfg == nil {
		return nil
	}
	names := make([]string, 0, len(cfg.Anvils))
	for name := range cfg.Anvils {
		names = append(names, name)
	}
	sort.Strings(names)

	var out []LegacyStageConflict
	for _, name := range names {
		resolved := cfg.ResolvedAssay(name)
		if !resolved.IsEnabled() {
			continue
		}
		var legacy []string
		for _, kv := range []struct{ key, val string }{
			{"assay.triage_provider", resolved.TriageProvider},
			{"assay.triage_model", resolved.TriageModel},
			{"assay.review_provider", resolved.ReviewProvider},
			{"assay.review_model", resolved.ReviewModel},
		} {
			if kv.val != "" {
				legacy = append(legacy, kv.key)
			}
		}
		stage := append(assayStageKeys("anvil", cfg.Anvils[name].StageProviders),
			assayStageKeys("settings", cfg.Settings.StageProviders)...)
		if len(legacy) == 0 || len(stage) == 0 {
			continue
		}
		lc := LegacyStageConflict{Anvil: name, LegacyKeys: legacy, StageKeys: stage}
		for _, rc := range ForAnvil(cfg, name).ResolvedChains() {
			switch rc.Source {
			case SourceLegacyAssayBlock:
				lc.LegacyWins = append(lc.LegacyWins, rc.Pass)
			case SourceProviderDefaults:
				// Neither key reaches this pass (e.g. only triage_provider is
				// set beside a stage key for logic), so neither "wins" it.
			default:
				lc.StageWins = append(lc.StageWins, rc.Pass)
			}
		}
		out = append(out, lc)
	}
	return out
}

// assayStageKeys lists the non-empty "assay" and "assay.*" keys of one
// stage_providers map, sorted and prefixed with the scope they came from.
func assayStageKeys(scope string, m map[string][]string) []string {
	var keys []string
	for k, v := range m {
		if len(v) == 0 {
			continue
		}
		if k == assayStageKey || strings.HasPrefix(k, assayStageKey+".") {
			keys = append(keys, scope+":"+k)
		}
	}
	sort.Strings(keys)
	return keys
}
