package assay

import (
	"github.com/Robin831/Forge/internal/config"
	"github.com/Robin831/Forge/internal/diff"
	"github.com/Robin831/Forge/internal/provider"
)

// Config is the resolved configuration the Assay review engine needs for a
// single review. It is deliberately decoupled from config.AssayConfig (the
// on-disk YAML shape) so the engine can be exercised in tests without loading
// real configuration. Build one from a config.AssayConfig via FromAssayConfig,
// or construct it directly in tests.
//
// IMPORTANT: every model identifier consumed by the engine comes from
// ModelTier or the TriageModel/ReviewModel hints — the package NEVER hard-codes
// a concrete model ID. When a model hint is empty the underlying provider
// chooses its own default model.
type Config struct {
	// ModelTier is a semantic label describing the desired model strength
	// (e.g. "default", "fast"). It is recorded for observability and may be
	// surfaced to operators; the concrete model identifiers are always the
	// TriageModel/ReviewModel hints below, never a literal baked into the code.
	ModelTier string

	// TriageProvider and ReviewProvider are provider specs (the same syntax as
	// settings.providers, e.g. "claude", "gemini/gemini-2.5-pro"). Empty falls
	// back to provider.Defaults(). TriageProvider drives the cheap scoping pass;
	// ReviewProvider drives the five deep passes.
	TriageProvider string
	ReviewProvider string

	// TriageModel and ReviewModel are model hints (provider-specific model
	// identifiers) used for the triage pass and the deep passes respectively.
	// Empty means "let the provider pick its default model".
	TriageModel string
	ReviewModel string

	// NitCap caps the number of Nit-severity findings retained after
	// aggregation. Values <= 0 mean "no cap".
	NitCap int

	// ShadowMode, when true, signals that the review must not produce public
	// side effects: Review still writes findings to pr_findings, but the caller
	// must not post them. Defaults to the safe value (true) via FromAssayConfig.
	ShadowMode bool

	// MaxDiffBytes caps the size of the diff embedded in pass prompts. Values
	// <= 0 fall back to diff.MaxBytes.
	MaxDiffBytes int

	// SkipPaths are doublestar globs whose files are excluded from review
	// (their hunks are dropped before the diff reaches any pass).
	SkipPaths []string

	// AutoGeneratedPatterns are doublestar globs whose hunks are filtered out
	// before review (machine-generated snapshots, etc.). Empty uses
	// diff.AutoGeneratedPatterns.
	AutoGeneratedPatterns []string

	// runner is the seam used to invoke a model for a single pass. When nil,
	// Review installs the default Smith-based runner. Tests in this package set
	// it directly (or via WithRunner) to a deterministic stub so no real model
	// process is spawned.
	runner PassRunner
}

// DefaultConfig returns a Config with conservative defaults: shadow mode on,
// no model hints (providers pick their own defaults), and the shared diff
// auto-generated filters.
func DefaultConfig() Config {
	return Config{
		ModelTier:             "default",
		ShadowMode:            true,
		NitCap:                0,
		MaxDiffBytes:          diff.MaxBytes,
		AutoGeneratedPatterns: diff.AutoGeneratedPatterns,
	}
}

// FromAssayConfig builds an engine Config from the resolved on-disk Assay
// configuration. Unset fields inherit the DefaultConfig values so the engine
// always has a usable configuration.
func FromAssayConfig(ac config.AssayConfig) Config {
	cfg := DefaultConfig()
	cfg.ShadowMode = ac.IsShadowMode()
	cfg.NitCap = ac.GetNitCap()
	if ac.ModelTier != "" {
		cfg.ModelTier = ac.ModelTier
	}
	cfg.TriageProvider = ac.TriageProvider
	cfg.ReviewProvider = ac.ReviewProvider
	cfg.TriageModel = ac.TriageModel
	cfg.ReviewModel = ac.ReviewModel
	if mdb := ac.GetMaxDiffBytes(); mdb > 0 {
		cfg.MaxDiffBytes = mdb
	}
	if len(ac.SkipPaths) > 0 {
		cfg.SkipPaths = ac.SkipPaths
	}
	return cfg
}

// WithRunner returns a copy of the Config with the given pass runner installed.
// External callers use this to inject a custom runner; the package's own tests
// may set the unexported field directly.
func (c Config) WithRunner(r PassRunner) Config {
	c.runner = r
	return c
}

// maxDiffBytes returns the effective diff size cap, applying the diff.MaxBytes
// default when unset.
func (c Config) maxDiffBytes() int {
	if c.MaxDiffBytes <= 0 {
		return diff.MaxBytes
	}
	return c.MaxDiffBytes
}

// autoGenPatterns returns the effective auto-generated file patterns, applying
// the shared default when unset.
func (c Config) autoGenPatterns() []string {
	if len(c.AutoGeneratedPatterns) == 0 {
		return diff.AutoGeneratedPatterns
	}
	return c.AutoGeneratedPatterns
}

// providerFor resolves the provider and model hint for the given tier. The
// model is taken exclusively from the configured hints (never hard-coded); an
// empty hint leaves Provider.Model unset so the provider uses its own default.
func (c Config) providerFor(tier string) provider.Provider {
	spec := c.ReviewProvider
	model := c.ReviewModel
	if tier == tierTriage {
		if c.TriageProvider != "" {
			spec = c.TriageProvider
		}
		if c.TriageModel != "" {
			model = c.TriageModel
		}
	}

	pv := provider.Provider{Kind: provider.Claude}
	if spec != "" {
		if list := provider.FromConfig([]string{spec}); len(list) > 0 {
			pv = list[0]
		}
	}
	if model != "" {
		pv.Model = model
	}
	return pv
}
