package assay

import "strings"

// SkipReasonNoReviewableChanges is the skipped_reason recorded for a run whose
// diff carried nothing for a pass to read once the shared generated-file filter
// and the anvil's own assay.skip_paths had been applied to it.
//
// It is a constant rather than a literal at each site because three of them
// have to agree: the engine sets it on the result, the daemon persists it in
// assay_runs.skipped_reason, and the PR summary and the activity feed render
// it. A skip that reads one way in the database and another on the PR is a skip
// nobody can audit.
const SkipReasonNoReviewableChanges = "no reviewable changes"

// shouldSkip decides whether a run should dispatch its passes at all, given the
// diff that survived filtering. It is called once, after the incremental
// scoping and both filters and before the triage session, and it is a pure
// function of that diff: the all-generated case needs no special handling here
// because the filter has already removed those files, and what it leaves behind
// is a diff with no hunks in it.
//
// Skipping is decided on hunks and not on the string being empty, because
// FilterAutoGenerated preserves any preamble ahead of the first "diff --git"
// block. A PR of nothing but lockfiles therefore comes back as a few bytes of
// commit header rather than as "", and a length test would have dispatched five
// sessions over it — the exact spend this skip exists to stop.
//
// It is deliberately the whole test: a diff with no "@@" carries no changed
// line for a finding to anchor to, so a pure rename, a mode change or a
// binary-only push is skipped for the same reason and with the same honesty.
func shouldSkip(filtered string) (reason string, skip bool) {
	if hasReviewableHunk(filtered) {
		return "", false
	}
	return SkipReasonNoReviewableChanges, true
}

// hasReviewableHunk reports whether a unified diff contains at least one hunk
// header. It walks the string by line index rather than strings.Split so a
// multi-megabyte diff is not copied into a slice of lines, and it matches only
// at the start of a line: a "@@" inside a hunk's own content arrives prefixed
// with a context or +/- marker, so a patch file under review cannot be mistaken
// for a hunk of its own. Matching too eagerly here fails safe anyway — the run
// reviews a diff it could have skipped.
func hasReviewableHunk(d string) bool {
	for rest := d; rest != ""; {
		var line string
		if nl := strings.IndexByte(rest, '\n'); nl >= 0 {
			line, rest = rest[:nl], rest[nl+1:]
		} else {
			line, rest = rest, ""
		}
		if strings.HasPrefix(line, "@@") {
			return true
		}
	}
	return false
}

// SkippedSummaryLine is the one-line verdict a skipped run posts on the PR, in
// the place a run with findings puts its severity tally.
//
// It exists because the alternative readings are both wrong. Posting the
// ordinary "no issues found" line would report a review that never ran as a
// clean bill of health, and posting nothing at all leaves the PR's most recent
// Assay comment describing an older head. So the comment says which of the two
// happened, in the same voice the partial-coverage note uses.
func SkippedSummaryLine(reason string) string {
	if reason == "" {
		reason = SkipReasonNoReviewableChanges
	}
	return "Assay (AI review): **skipped** — " + reason +
		". Nothing was left to read once generated files and this repository's excluded paths were filtered out, so no code was reviewed: this is not a clean bill of health."
}
