package assay

import (
	"context"
	"strings"
	"testing"
)

// --- shouldSkip ------------------------------------------------------------

func TestShouldSkip(t *testing.T) {
	cases := []struct {
		name     string
		diff     string
		wantSkip bool
	}{
		{name: "nil-equivalent empty diff", diff: "", wantSkip: true},
		{name: "whitespace only", diff: "\n  \n\t\n", wantSkip: true},
		{
			// What an all-generated PR looks like AFTER FilterAutoGenerated:
			// every block gone, the preamble it preserves left behind. A
			// length test would call this a diff and dispatch five sessions.
			name:     "preamble left by the generated-file filter",
			diff:     "commit 9f1c2ab\nAuthor: someone\n",
			wantSkip: true,
		},
		{
			name:     "file headers with no hunks",
			diff:     "diff --git a/old.go b/new.go\nsimilarity index 100%\nrename from old.go\nrename to new.go\n",
			wantSkip: true,
		},
		{
			name:     "binary file, no hunks",
			diff:     "diff --git a/logo.png b/logo.png\nBinary files a/logo.png and b/logo.png differ\n",
			wantSkip: true,
		},
		{
			name:     "one real hunk",
			diff:     "diff --git a/main.go b/main.go\n--- a/main.go\n+++ b/main.go\n@@ -1,3 +1,4 @@\n+x := 1\n",
			wantSkip: false,
		},
		{
			// The one real hunk is the last block; the generated ones ahead of
			// it are already gone. Scanning must not stop at the first block.
			name:     "one real hunk after a hunkless block",
			diff:     "diff --git a/old.go b/new.go\nrename from old.go\nrename to new.go\ndiff --git a/main.go b/main.go\n@@ -1 +1,2 @@\n+x := 1\n",
			wantSkip: false,
		},
		{
			// A patch file under review carries its own "@@" lines, but as
			// diff CONTENT: prefixed with +/-/space. They must not be read as
			// this diff's hunk headers... and the enclosing hunk header, which
			// is real, means the answer is "do not skip" either way.
			name:     "hunk markers inside content",
			diff:     "diff --git a/fix.patch b/fix.patch\n@@ -1 +1,2 @@\n+@@ -3,4 +3,5 @@\n",
			wantSkip: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			reason, skip := shouldSkip(tc.diff)
			if skip != tc.wantSkip {
				t.Fatalf("shouldSkip() skip = %v, want %v", skip, tc.wantSkip)
			}
			switch {
			case tc.wantSkip && reason != SkipReasonNoReviewableChanges:
				t.Errorf("reason = %q, want %q", reason, SkipReasonNoReviewableChanges)
			case !tc.wantSkip && reason != "":
				t.Errorf("reason = %q, want empty on a run that is not skipped", reason)
			}
		})
	}
}

// --- Review: the skip reaches the result and costs nothing -----------------

// generatedOnlyDiff is a diff of nothing but files the built-in generated-file
// filter matches. It is what a dependency-bump push looks like.
const generatedOnlyDiff = "diff --git a/package-lock.json b/package-lock.json\n" +
	"--- a/package-lock.json\n+++ b/package-lock.json\n" +
	"@@ -1,3 +1,3 @@\n-  \"version\": \"1.0.0\"\n+  \"version\": \"1.0.1\"\n" +
	"diff --git a/web/yarn.lock b/web/yarn.lock\n--- a/web/yarn.lock\n+++ b/web/yarn.lock\n" +
	"@@ -1 +1 @@\n-old\n+new\n"

func TestReviewSkipsWhenEveryFileWasGenerated(t *testing.T) {
	runner := newScriptRunner(nil)
	cfg := DefaultConfig().WithRunner(runner.run)

	req := testRequest()
	req.Diff = generatedOnlyDiff

	res, err := Review(context.Background(), req, openTestDB(t), cfg)
	if err != nil {
		t.Fatalf("Review: %v", err)
	}
	if res.SkippedReason != SkipReasonNoReviewableChanges {
		t.Errorf("SkippedReason = %q, want %q", res.SkippedReason, SkipReasonNoReviewableChanges)
	}
	// Complete, not failed: the head was considered, and Failed would mean the
	// daemon's LastReviewedSHA gate re-dispatches this same skip forever.
	if res.Status != RunStatusComplete {
		t.Errorf("Status = %q, want %q", res.Status, RunStatusComplete)
	}
	// The whole point: not one session was spawned.
	if n := len(runner.calls); n != 0 {
		t.Errorf("expected no pass sessions, got %d: %+v", n, runner.calls)
	}
	if len(res.Findings) != 0 || res.CostUSD != 0 || res.TotalPasses != 0 {
		t.Errorf("expected an empty, free run; got %d findings, $%.2f, %d passes",
			len(res.Findings), res.CostUSD, res.TotalPasses)
	}
	// The elision counts survive the early return: they are what the log line
	// uses to say what the diff had consisted of.
	if len(res.ElidedFiles) != 2 || res.ElidedBytes == 0 {
		t.Errorf("expected 2 elided files with a byte count, got %v (%d bytes)", res.ElidedFiles, res.ElidedBytes)
	}
	if txt := res.StatusText(); !strings.Contains(txt, "skipped") {
		t.Errorf("StatusText() = %q, want it to report the skip", txt)
	}
}

func TestReviewSkipsWhenSkipPathsRemoveEverything(t *testing.T) {
	runner := newScriptRunner(nil)
	cfg := DefaultConfig().WithRunner(runner.run)
	cfg.SkipPaths = []string{"docs/**"}

	req := testRequest()
	req.Diff = "diff --git a/docs/guide.md b/docs/guide.md\n--- a/docs/guide.md\n+++ b/docs/guide.md\n@@ -1 +1 @@\n-old\n+new\n"

	res, err := Review(context.Background(), req, openTestDB(t), cfg)
	if err != nil {
		t.Fatalf("Review: %v", err)
	}
	if res.SkippedReason == "" {
		t.Fatal("expected the run to be skipped when skip_paths removed the whole diff")
	}
	if n := len(runner.calls); n != 0 {
		t.Errorf("expected no pass sessions, got %d", n)
	}
	if len(res.SkippedFiles) != 1 {
		t.Errorf("expected the excluded file reported, got %v", res.SkippedFiles)
	}
}

func TestReviewDoesNotSkipWhenOneRealHunkSurvives(t *testing.T) {
	runner := newScriptRunner(baseScript(triageJSON(t, nil, ""), nil))
	cfg := DefaultConfig().WithRunner(runner.run)

	req := testRequest()
	req.Diff = generatedOnlyDiff +
		"diff --git a/main.go b/main.go\n--- a/main.go\n+++ b/main.go\n@@ -1 +1,2 @@\n+x := 1\n"

	res, err := Review(context.Background(), req, openTestDB(t), cfg)
	if err != nil {
		t.Fatalf("Review: %v", err)
	}
	if res.SkippedReason != "" {
		t.Fatalf("expected no skip, got %q", res.SkippedReason)
	}
	if res.Status != RunStatusComplete {
		t.Errorf("Status = %q, want %q", res.Status, RunStatusComplete)
	}
	if res.TotalPasses != len(deepPasses) {
		t.Errorf("TotalPasses = %d, want %d", res.TotalPasses, len(deepPasses))
	}
	// Triage plus every deep pass ran over the surviving hunk.
	if n := len(runner.calls); n != len(deepPasses)+1 {
		t.Errorf("expected %d sessions, got %d", len(deepPasses)+1, n)
	}
	if len(res.ElidedFiles) != 2 {
		t.Errorf("expected the generated files still elided, got %v", res.ElidedFiles)
	}
}

// --- surfacing -------------------------------------------------------------

func TestSkippedSummaryLineDoesNotReadAsAReview(t *testing.T) {
	line := SkippedSummaryLine(SkipReasonNoReviewableChanges)
	if !strings.Contains(line, "skipped") || !strings.Contains(line, SkipReasonNoReviewableChanges) {
		t.Errorf("summary line does not name the skip: %q", line)
	}
	if strings.Contains(line, "no issues found") {
		t.Errorf("summary line reads as a clean review: %q", line)
	}
	// An empty reason still produces a line that says a skip happened, rather
	// than a dangling dash.
	if fallback := SkippedSummaryLine(""); !strings.Contains(fallback, SkipReasonNoReviewableChanges) {
		t.Errorf("SkippedSummaryLine(\"\") = %q, want the default reason", fallback)
	}
}

func TestRunEventReportsSkipInsteadOfFindingCount(t *testing.T) {
	msg := RunEvent{
		PRNumber:      347,
		Status:        RunStatusComplete,
		SkippedReason: SkipReasonNoReviewableChanges,
	}.Message()
	if !strings.Contains(msg, "skipped: "+SkipReasonNoReviewableChanges) {
		t.Errorf("event message does not name the skip: %q", msg)
	}
	if strings.Contains(msg, "0 findings") {
		t.Errorf("event message reads as a clean review: %q", msg)
	}
}

// --- posting ---------------------------------------------------------------

// A skipped run posts the one thing the PR needs — the summary saying the
// review was skipped — and stops there. In particular it must not put a
// previously posted finding one miss closer to being auto-resolved: nothing
// re-examined that code, so its absence from this run's (empty) finding set is
// not evidence of anything.
func TestPostSkippedRunSummarisesWithoutTouchingThreads(t *testing.T) {
	db := newTestDB(t)
	gh := newStubGh()
	resolver := &stubResolver{threadID: "THREAD_1"}
	p := newPoster(db, gh.exec, resolver)

	mustInsert(t, db, "anvil", 9, Finding{
		File: "live.go", Anchor: "live.go:1", Hash: "live", Severity: SeverityImportant, Title: "x",
	})
	mustMarkPosted(t, db, "live", 111)
	if err := db.IncrementConsecutiveMiss("live"); err != nil {
		t.Fatal(err)
	}

	res, err := p.Post(context.Background(), Config{}, PostRequest{
		Anvil:         "anvil",
		PRNumber:      9,
		HeadSHA:       "sha9",
		SummaryLine:   SkippedSummaryLine(SkipReasonNoReviewableChanges),
		SkippedReason: SkipReasonNoReviewableChanges,
	})
	if err != nil {
		t.Fatalf("Post: %v", err)
	}
	if !res.SummaryPosted {
		t.Fatal("a skipped run must still post the summary saying so")
	}
	if body := gh.summaryBody(); !strings.Contains(body, "skipped") {
		t.Errorf("summary does not report the skip:\n%s", body)
	}
	if res.Resolved != 0 || len(resolver.resolved) != 0 {
		t.Errorf("a skipped run must resolve nothing, got %d (%v)", res.Resolved, resolver.resolved)
	}
	if _, _, misses, resolved := readFindingRow(t, db, "live"); resolved || misses != 1 {
		t.Errorf("live finding should be untouched at misses=1, got misses=%d resolved=%v", misses, resolved)
	}
}
