package warden

import (
	"strings"
	"testing"
)

func TestFilterAutoGeneratedFiles_RemovesEFCoreDesignerSnapshot(t *testing.T) {
	designerHunk := strings.Repeat("+// auto-generated snapshot line\n", 4000) // ~120KB
	migrationHunk := "+using Foo.Bar;\n+public partial class AddWidget : Migration {}\n"

	diff := "diff --git a/src/Migrations/20260423_AddWidget.Designer.cs b/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"--- a/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"+++ b/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"@@ -1 +1,4000 @@\n" +
		designerHunk +
		"diff --git a/src/Migrations/20260423_AddWidget.cs b/src/Migrations/20260423_AddWidget.cs\n" +
		"--- a/src/Migrations/20260423_AddWidget.cs\n" +
		"+++ b/src/Migrations/20260423_AddWidget.cs\n" +
		"@@ -1 +1,2 @@\n" +
		migrationHunk

	filtered, elided := filterAutoGeneratedFiles(diff, autoGeneratedDiffPatterns)

	if len(elided) != 1 {
		t.Fatalf("expected 1 elided file, got %d: %v", len(elided), elided)
	}
	if elided[0] != "src/Migrations/20260423_AddWidget.Designer.cs" {
		t.Errorf("unexpected elided path: %q", elided[0])
	}
	if strings.Contains(filtered, "auto-generated snapshot line") {
		t.Error("filtered diff should not contain designer snapshot content")
	}
	if !strings.Contains(filtered, "AddWidget : Migration") {
		t.Error("filtered diff should still contain the hand-written migration")
	}
	if len(filtered) >= 50000 {
		t.Errorf("filtered diff should be small after removing designer snapshot; got %d bytes", len(filtered))
	}
}

func TestFilterAutoGeneratedFiles_RemovesModelSnapshot(t *testing.T) {
	diff := "diff --git a/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs b/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs\n" +
		"--- a/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs\n" +
		"+++ b/src/Data/Migrations/ApplicationDbContextModelSnapshot.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// snapshot contents\n" +
		"diff --git a/src/Program.cs b/src/Program.cs\n" +
		"--- a/src/Program.cs\n" +
		"+++ b/src/Program.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// real change\n"

	filtered, elided := filterAutoGeneratedFiles(diff, autoGeneratedDiffPatterns)

	if len(elided) != 1 || elided[0] != "src/Data/Migrations/ApplicationDbContextModelSnapshot.cs" {
		t.Errorf("expected ApplicationDbContextModelSnapshot.cs to be elided; got %v", elided)
	}
	if strings.Contains(filtered, "snapshot contents") {
		t.Error("filtered diff should not contain model snapshot content")
	}
	if !strings.Contains(filtered, "real change") {
		t.Error("filtered diff should retain Program.cs hunk")
	}
}

func TestFilterAutoGeneratedFiles_PassthroughWhenNoMatches(t *testing.T) {
	diff := "diff --git a/src/Program.cs b/src/Program.cs\n" +
		"--- a/src/Program.cs\n" +
		"+++ b/src/Program.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// change\n"

	filtered, elided := filterAutoGeneratedFiles(diff, autoGeneratedDiffPatterns)

	if len(elided) != 0 {
		t.Errorf("expected no elisions, got %v", elided)
	}
	if filtered != diff {
		t.Error("diff should be returned unchanged when no files match")
	}
}

func TestFilterAutoGeneratedFiles_DoesNotMatchDesignerOutsideMigrations(t *testing.T) {
	// A hand-written file named MyDesigner.cs at the repo root must NOT match —
	// the pattern explicitly requires the Migrations/ directory prefix.
	diff := "diff --git a/MyDesigner.cs b/MyDesigner.cs\n" +
		"--- a/MyDesigner.cs\n" +
		"+++ b/MyDesigner.cs\n" +
		"@@ -1 +1 @@\n" +
		"+// hand-written\n"

	filtered, elided := filterAutoGeneratedFiles(diff, autoGeneratedDiffPatterns)

	if len(elided) != 0 {
		t.Errorf("hand-written Designer.cs outside Migrations/ should not be elided; got %v", elided)
	}
	if !strings.Contains(filtered, "hand-written") {
		t.Error("filtered diff should retain hand-written file")
	}
}

func TestFilterAutoGeneratedFiles_EmptyInputs(t *testing.T) {
	if out, elided := filterAutoGeneratedFiles("", autoGeneratedDiffPatterns); out != "" || elided != nil {
		t.Errorf("empty diff should pass through unchanged; got %q, %v", out, elided)
	}
	diff := "diff --git a/x b/x\n@@ -0 +1 @@\n+y\n"
	if out, elided := filterAutoGeneratedFiles(diff, nil); out != diff || elided != nil {
		t.Errorf("nil patterns should pass through unchanged")
	}
}

func TestBuildReviewPrompt_OmitsDesignerSnapshot(t *testing.T) {
	designerHunk := strings.Repeat("+// auto-generated snapshot line\n", 4000) // ~120KB
	diff := "diff --git a/src/Migrations/20260423_AddWidget.Designer.cs b/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"--- a/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"+++ b/src/Migrations/20260423_AddWidget.Designer.cs\n" +
		"@@ -1 +1,4000 @@\n" +
		designerHunk +
		"diff --git a/src/Migrations/20260423_AddWidget.cs b/src/Migrations/20260423_AddWidget.cs\n" +
		"--- a/src/Migrations/20260423_AddWidget.cs\n" +
		"+++ b/src/Migrations/20260423_AddWidget.cs\n" +
		"@@ -1 +1 @@\n" +
		"+public partial class AddWidget : Migration {}\n"

	prompt := buildReviewPrompt("Forge-e6wl", "Add widget table", "", diff, t.TempDir(), "")

	if strings.Contains(prompt, "auto-generated snapshot line") {
		t.Error("prompt should not contain the elided designer snapshot content")
	}
	if !strings.Contains(prompt, "AddWidget : Migration") {
		t.Error("prompt should still contain the real migration hunk")
	}
	if !strings.Contains(prompt, "auto-generated files were omitted") {
		t.Error("prompt should note that auto-generated files were omitted")
	}
	if !strings.Contains(prompt, "20260423_AddWidget.Designer.cs") {
		t.Error("prompt should name the elided file so the reviewer sees what was dropped")
	}
	if strings.Contains(prompt, "diff truncated,") {
		t.Error("prompt should not trigger truncation once the designer snapshot is filtered")
	}
}

func TestBuildReviewPrompt_TruncatesWhenFilteredDiffStillTooLarge(t *testing.T) {
	// A legitimate non-auto-generated diff larger than the cap should still be
	// truncated, with both the elision note and the truncation note visible.
	designerHunk := strings.Repeat("+// snapshot\n", 200)
	bigRealHunk := strings.Repeat("+// real code line\n", 20000) // > 250KB
	diff := "diff --git a/src/Migrations/20260423_X.Designer.cs b/src/Migrations/20260423_X.Designer.cs\n" +
		"--- a/src/Migrations/20260423_X.Designer.cs\n" +
		"+++ b/src/Migrations/20260423_X.Designer.cs\n" +
		"@@ -1 +1,200 @@\n" +
		designerHunk +
		"diff --git a/src/Bloat.cs b/src/Bloat.cs\n" +
		"--- a/src/Bloat.cs\n" +
		"+++ b/src/Bloat.cs\n" +
		"@@ -1 +1,20000 @@\n" +
		bigRealHunk

	prompt := buildReviewPrompt("Forge-e6wl", "Big change", "", diff, t.TempDir(), "")

	if !strings.Contains(prompt, "auto-generated files were omitted") {
		t.Error("prompt should note that auto-generated files were omitted")
	}
	if !strings.Contains(prompt, "diff truncated,") {
		t.Error("prompt should still truncate when the filtered diff exceeds the cap")
	}
}
