package gitfail

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/Robin831/Forge/internal/termtext"
	"github.com/Robin831/Forge/internal/textfmt"
)

// MaxPathsListed bounds the enumerated path list in one message by COUNT. The
// list exists so an operator RECOGNISES the condition at a glance; a checkout
// with two hundred modified files rendered in full is the same wall of text the
// bounded git evidence beside it is already kept away from, and it would push
// the remediation command off the end of a Needs Attention row.
const MaxPathsListed = 20

// MaxPathsBytes bounds the same list by SIZE, and is the binding one on deep
// paths: twenty paths at MaxPathLen each is larger than the whole-detail bound
// a caller sizes its message in, so a count cap alone would let the list
// overrun the row it is a component of.
const MaxPathsBytes = 400

// MaxCommandPathsListed bounds the paths written into a remediation command. A
// command is copy-pasted, not read: past a handful of paths an operator works
// from `git status` anyway, and a line that wraps four times reads as noise
// rather than as the one thing to run.
const MaxCommandPathsListed = 5

// MaxCommandPathspecBytes is the same bound by size, for the same reason as
// MaxPathsBytes. What it must never do is CUT a path — a truncated one names a
// different file — so Pathspec stops before the path that would cross it and
// reports how many it covered.
const MaxCommandPathspecBytes = 320

// MaxPathLen bounds one rendered path. Paths come out of a checkout Forge did
// not author, so this is the same treatment git's own words get: bounded, and
// stripped of anything a terminal would interpret.
const MaxPathLen = 160

// KnownPath annotates a path an operator will see on a Forge-managed checkout
// that is EXPECTED to differ from upstream. Naming them inline is the
// difference between a message an operator recognises in one read and one that
// sends them to inspect a file that is doing exactly what it should.
//
// KnownPaths is an ordered slice rather than a map so two suffixes that could
// both match one path resolve the same way on every run — a rendered message is
// compared against the previous one by an operator, and by the callers that
// refresh a persisted row from it.
type KnownPath struct {
	// Suffix is matched against the whole path or against a trailing path
	// segment boundary, never as a bare substring: `foo.beads/config.yaml` is a
	// different file from `.beads/config.yaml`.
	Suffix string
	Note   string
}

var KnownPaths = []KnownPath{
	{".beads/config.yaml", "pod-local sync.remote override — expected to differ from upstream, leave it"},
	{".beads/.gitignore", "regenerated by bd — safe to discard"},
}

// RunGitFunc runs one git command in repoDir and returns its stdout. Callers
// supply their own, because how git is invoked — the deadline, the stripped
// environment, the shape of the error — is theirs to decide; what is shared is
// what to ask it and how to read the answer.
type RunGitFunc func(ctx context.Context, repoDir string, args ...string) ([]byte, error)

// DirtyPaths enumerates the working-tree paths that differ from HEAD in
// repoDir, sorted and deduplicated.
//
// It reads `git status --porcelain -z`, which reports staged, unstaged,
// untracked and unmerged entries in one pass — the four kinds that between them
// cover every tree condition a blocked command can be sitting on. There is
// deliberately no `git diff --name-only` fallback: that command answers a strict
// SUBSET of this one, so an empty result here means a clean tree rather than a
// question still to be asked.
//
// `-z` rather than the plain short format because the plain one is ambiguous on
// exactly the paths this package must get right: it C-quotes a path containing a
// space and separates a rename's two paths with ` -> `, which is itself a legal
// substring of a filename, so `notes -> ../secrets.env` and
// `"arrow -> name.txt"` both parse to something that is not a file in the tree —
// and a path that is not a file in the tree is a pathspec that makes the
// remediation command an operator is told to paste fail outright. Under `-z`
// paths arrive verbatim, NUL-separated, and a rename is two records.
//
// A wholly untracked directory is reported by git as the directory itself
// rather than as its contents, which is left as-is: it is the bound that keeps a
// checkout with a large untracked tree from rendering every file in it, and a
// directory is exactly as recognisable to an operator and exactly as usable in a
// pathspec.
//
// A failure is returned but should never be fatal to the caller: a message is
// worth strictly more with the paths in it and is still worth sending without
// them, so callers degrade to an empty list.
func DirtyPaths(ctx context.Context, repoDir string, run RunGitFunc) ([]string, error) {
	if repoDir == "" || run == nil {
		return nil, nil
	}
	out, err := run(ctx, repoDir, "status", "--porcelain", "-z")
	if err != nil {
		return nil, err
	}
	return ParsePorcelainZ(string(out)), nil
}

// ParsePorcelainZ extracts the paths from `git status --porcelain -z` output.
//
// Each record is two status columns, a space, and the path — unquoted, however
// the path is spelled, because `-z` is the format that has no quoting to undo.
// A rename or copy (`R`/`C` in either column) is TWO records, the current path
// first and the original after it, so the second is consumed here: the path that
// matters is the one present in the tree, which is the one a pathspec has to
// name, and the original no longer exists for a pathspec to match.
//
// `rec[3:]` IS the path, taken whole and never trimmed. The record carries no
// terminator of its own — the NUL is the separator Split has already consumed —
// so there is nothing to trim off, and trimming anyway would rewrite a legal
// filename (`dir/x ` with a trailing space, ` leading.go`) into a name that is
// not a file in the tree. That is not merely a cosmetic loss: Pathspec only
// writes a path into a pasteable remediation when sanitization left it
// BYTE-IDENTICAL, and a pre-trimmed path passes that guard and puts a
// nonexistent file into a command an operator is told to run. Untrimmed, it
// fails the guard and the command degrades to an honest `<path>` template.
func ParsePorcelainZ(out string) []string {
	records := strings.Split(out, "\x00")
	seen := map[string]struct{}{}
	var paths []string
	for i := 0; i < len(records); i++ {
		rec := records[i]
		// "XY P" is the shortest record that can carry a path, which also drops
		// the empty trailing record git's final NUL leaves behind.
		if len(rec) < 4 {
			continue
		}
		if isRenameOrCopy(rec[0]) || isRenameOrCopy(rec[1]) {
			// The original path follows as its own record. Skipping it here is
			// what keeps it from being read as a status entry of its own — its
			// first three bytes are part of a filename, not status columns. It is
			// consumed by INDEX rather than by inspection, so a short original
			// (`ab`) is skipped as reliably as a long one.
			i++
		}
		p := rec[3:]
		if _, dup := seen[p]; dup {
			continue
		}
		seen[p] = struct{}{}
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}

// isRenameOrCopy reports whether a porcelain status column says a second,
// original path follows the entry.
func isRenameOrCopy(c byte) bool { return c == 'R' || c == 'C' }

// SafePath renders one path for an operator-facing surface. The path came out
// of somebody's checkout, and the message it lands in is written to daemon.log
// and to an activity-feed row Hearth wraps without stripping, so it gets the
// same treatment as git's own words: escape sequences removed whole, line breaks
// spaced, and a bound on the length.
func SafePath(p string) string {
	clean := strings.Join(strings.Fields(termtext.Line(p)), " ")
	return textfmt.TruncateRunes(clean, MaxPathLen)
}

// Annotate returns the inline explanation for a path an operator is expected to
// see modified, or "" for one they are not.
func Annotate(p string) string {
	for _, known := range KnownPaths {
		if p == known.Suffix || strings.HasSuffix(p, "/"+known.Suffix) {
			return known.Note
		}
	}
	return ""
}

// ExpectedPathNames renders the permanently-modified files a Forge-managed
// checkout legitimately carries, for a message that has no enumerated list to
// annotate. It is read off KnownPaths rather than written out again, so a new
// entry there cannot leave one sentence naming a set the rest of the package no
// longer agrees with.
func ExpectedPathNames() string {
	names := make([]string, 0, len(KnownPaths))
	for _, known := range KnownPaths {
		names = append(names, "`"+known.Suffix+"`")
	}
	switch len(names) {
	case 0:
		return "anything this checkout is meant to carry"
	case 1:
		return names[0]
	default:
		return strings.Join(names[:len(names)-1], ", ") + " and " + names[len(names)-1]
	}
}

// IsExpectedPath reports whether a path is one of the permanently modified files
// a Forge-managed checkout legitimately carries. They are excluded from a
// remediation command: telling an operator to stash the pod-local
// `.beads/config.yaml` is telling them to break the checkout's beads connection.
func IsExpectedPath(p string) bool { return Annotate(p) != "" }

// RenderPath renders one entry of the enumerated list: the sanitized path plus,
// for one an operator is expected to see modified, the inline note saying so.
func RenderPath(p string) string {
	entry := SafePath(p)
	if note := Annotate(p); note != "" {
		entry += " (" + note + ")"
	}
	return entry
}

// ListedPaths is the prefix of the path set a message actually shows — both caps
// applied, count and size. It is the one definition of that prefix, so a
// sentence written about "the paths above" is written about the paths that are
// above it, and so the rendered list cannot outgrow the budget ListedPaths was
// measured against.
//
// The first path is always listed, whatever it costs: an enumeration block with
// a count and no paths in it says less than no block at all. It cannot overrun
// the budget on its own, since SafePath bounds one path to MaxPathLen bytes and
// an annotation is one of the fixed notes above.
func ListedPaths(paths []string) []string {
	budget := MaxPathsBytes
	for i, p := range paths {
		if i == MaxPathsListed {
			return paths[:i]
		}
		cost := len(RenderPath(p)) + len(", ")
		if i > 0 && cost > budget {
			return paths[:i]
		}
		budget -= cost
	}
	return paths
}

// RenderPaths renders the enumerated list, annotated, capped, with the full
// count beside it so a truncated list never reads as the whole story.
func RenderPaths(paths []string) string {
	shown := ListedPaths(paths)
	extra := len(paths) - len(shown)
	rendered := make([]string, 0, len(shown))
	for _, p := range shown {
		rendered = append(rendered, RenderPath(p))
	}
	list := strings.Join(rendered, ", ")
	if extra > 0 {
		list += fmt.Sprintf(", and %d more", extra)
	}
	return list
}

// ShellQuote renders a path as one shell word. Most paths need no quoting at
// all, which is what keeps the common remediation line readable.
func ShellQuote(p string) string {
	if p != "" && !strings.ContainsAny(p, " \t\n'\"\\$`&;|<>()*?[]{}#~!") {
		return p
	}
	return "'" + strings.ReplaceAll(p, "'", `'\''`) + "'"
}

// Pathspec renders the pathspec for a remediation command, or "" when no usable
// one can be built. The second return is how many of the paths it was handed
// that pathspec actually covers: past MaxCommandPathsListed (or
// MaxCommandPathspecBytes) it is not all of them, and the caller must not then
// describe the command as dealing with the whole set — a pasted line that clears
// five of twelve blocking paths leaves the condition in place while reading like
// the fix, which is the one way a remediation can be worse than none. It is a
// count rather than a bool because the caller says the number out loud, and two
// caps mean the number is not always MaxCommandPathsListed.
//
// A path is only written into a command if sanitization left it BYTE-IDENTICAL:
// a command is meant to be pasted and run, and a path silently truncated or with
// a rune replaced names a different file — or, with the wrong luck, a wider set
// than the operator read. Where that cannot be guaranteed for every path the
// command would carry, the caller falls back to a command with a placeholder,
// which is honest about being a template.
func Pathspec(paths []string) (string, int) {
	usable := make([]string, 0, len(paths))
	budget := MaxCommandPathspecBytes
	for _, p := range paths {
		if SafePath(p) != p {
			return "", 0
		}
		quoted := ShellQuote(p)
		// Stop BEFORE the path that would cross the budget rather than cutting
		// it: half a path is a pathspec naming a different file, or none.
		if len(usable) > 0 && len(quoted)+1 > budget {
			break
		}
		budget -= len(quoted) + 1
		usable = append(usable, quoted)
		if len(usable) == MaxCommandPathsListed {
			break
		}
	}
	if len(usable) == 0 {
		return "", 0
	}
	return strings.Join(usable, " "), len(usable)
}

// UnexpectedPaths drops the permanently modified files a checkout is supposed to
// carry, leaving what an operator actually has to deal with.
func UnexpectedPaths(paths []string) []string {
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		if !IsExpectedPath(p) {
			out = append(out, p)
		}
	}
	return out
}
